/* 1001 种软骨鱼 — 母版数据集（550 条：鲨、鳐、银鲛）
   来源 Wikidata 软骨鱼纲 Q25371，要求「有中文名 + 有真实照片」，此标准下全球上限即 554。 */
window.SHARK_DATA = [
{"id": 1, "name": "丁字双髻鲨", "name_en": "", "sci": "Eusphyra blochii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 3, "name": "丁氏双鳍电鳐", "name_en": "Blackspotted numbfish", "sci": "Narcine timlei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 4, "name": "丘布特凯克鲨", "name_en": "Carcharocles chubutensis", "sci": "Carcharodon subauriculatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 5, "name": "东京电鳐", "name_en": "", "sci": "Torpedo tokionis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 6, "name": "东太平洋绒毛鲨", "name_en": "swellshark", "sci": "Cephaloscyllium ventriosum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 7, "name": "中华光尾鲨", "name_en": "South China catshark", "sci": "Apristurus sinensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 8, "name": "中国团扇鳐", "name_en": "fanray", "sci": "Platyrhina sinensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 9, "name": "中国魟", "name_en": "Chinese stingray", "sci": "Dasyatis sinensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 10, "name": "中間長吻鰩", "name_en": "", "sci": "Dipturus intermedius", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 11, "name": "乌鲨", "name_en": "Blackbelly lanternshark", "sci": "Etmopterus lucifer", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 12, "name": "乔氏银鲛", "name_en": "", "sci": "Chimaera jordani", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 13, "name": "云纹电鳐", "name_en": "Gulf torpedo", "sci": "Torpedo sinuspersici", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 14, "name": "亮尾拟小鳍鲨", "name_en": "taillight shark", "sci": "Euprotomicroides zantedeschia", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 15, "name": "伊氏锯尾鲨", "name_en": "Gecko catshark", "sci": "Galeus eastmani", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 16, "name": "低鰭刺鯊", "name_en": "lowfin gulper shark", "sci": "Centrophorus lusitanicus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 17, "name": "何氏鳐", "name_en": "", "sci": "Okamejei hollandi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 18, "name": "佛氏虎鯊", "name_en": "horn shark", "sci": "Heterodontus francisci", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 19, "name": "佩氏真鲨", "name_en": "Carcharhinus perezii", "sci": "Carcharhinus perezi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 20, "name": "侏儒角鯊", "name_en": "Dwarf lanternshark", "sci": "Etmopterus perryi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 21, "name": "侏斑鬚鯊", "name_en": "dwarf spotted wobbegong", "sci": "Orectolobus parvimaculatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 22, "name": "兇猛砂錐齒鯊", "name_en": "smalltooth sand tiger", "sci": "Odontaspis ferox", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 23, "name": "光滑強鰭鳐", "name_en": "Southern banded guitarfish", "sci": "Zapteryx xyster", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 24, "name": "光滑長吻鰩", "name_en": "Barndoor skate", "sci": "Dipturus laevis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 25, "name": "光澤深鰩", "name_en": "", "sci": "Pavoraja nitida", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 26, "name": "光背真鲨", "name_en": "Pacific smalltail shark", "sci": "Carcharhinus cerdale", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 27, "name": "光背長吻鰩", "name_en": "New Zealand smooth skate", "sci": "Dipturus innominatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 28, "name": "光鳞鲨", "name_en": "tawny nurse shark", "sci": "Nebrius ferrugineus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 29, "name": "光齒真鯊", "name_en": "Smoothtooth blacktip shark", "sci": "Carcharhinus leiodon", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 30, "name": "克氏指鳐", "name_en": "", "sci": "Dactylobatus clarkii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 31, "name": "兔子魚", "name_en": "", "sci": "Chimaera monstrosa", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 32, "name": "公牛鯊", "name_en": "", "sci": "Carcharhinus leucas", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 33, "name": "六鳃锯鲨", "name_en": "sixgill sawshark", "sci": "Pliotrema warreni", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 34, "name": "六鳃魟", "name_en": "sixgill stingray", "sci": "Hexatrygon bickelli", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 35, "name": "冰島鋸尾鯊", "name_en": "Mouse catshark", "sci": "Galeus murinus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 36, "name": "利氏龍紋鱝", "name_en": "African wedgefish", "sci": "Rhynchobatus luebberti", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 37, "name": "刺網鰩", "name_en": "Spiny deepsea skate", "sci": "Brochiraja spinifera", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 38, "name": "剑鼻鲨属", "name_en": "Daggernose shark", "sci": "Isogomphodon oxyrhynchus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 39, "name": "加勒比乌鲨", "name_en": "Caribbean lanternshark", "sci": "Etmopterus hillianus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 40, "name": "加勒比尖背角鯊", "name_en": "Caribbean roughshark", "sci": "Oxynotus caribbaeus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 41, "name": "加勒比斜鋸牙鯊", "name_en": "Caribbean sharpnose shark", "sci": "Rhizoprionodon porosus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 42, "name": "加州大電鱝", "name_en": "Pacific electric ray", "sci": "Torpedo californica", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 43, "name": "加州扁鲨", "name_en": "", "sci": "Squatina californica", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 44, "name": "加州星鯊", "name_en": "Grey smooth-hound", "sci": "Mustelus californicus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 45, "name": "加州鲼", "name_en": "bat ray", "sci": "Myliobatis californica", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 46, "name": "加拉帕戈斯真鲨", "name_en": "Galapagos shark", "sci": "Carcharhinus galapagensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 47, "name": "加氏白鰩", "name_en": "", "sci": "Leucoraja garmani", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 48, "name": "勃氏角鯊", "name_en": "Longnose spurdog", "sci": "Squalus blainville", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 49, "name": "匀棘深水鳐", "name_en": "", "sci": "Bathyraja isotrachys", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 50, "name": "北極鈍頭鳐", "name_en": "Arctic skate", "sci": "Amblyraja hyperborea", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 51, "name": "北河露齒鯊", "name_en": "Northern river shark", "sci": "Glyphis garricki", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 52, "name": "北美星鯊", "name_en": "Gulf smoothhound", "sci": "Mustelus sinusmexicanus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 53, "name": "半帶皺唇鯊", "name_en": "leopard shark", "sci": "Triakis semifasciata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 54, "name": "半鋸鯊", "name_en": "", "sci": "Hemipristis serra", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 55, "name": "半鋸齒鯊", "name_en": "Snaggletooth shark", "sci": "Hemipristis elongata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 56, "name": "南方烏鯊", "name_en": "Southern lanternshark", "sci": "Etmopterus granulosus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 57, "name": "南方田氏鯊", "name_en": "Deania quadrispinosum", "sci": "Deania quadrispinosa", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 58, "name": "南方龙纹鲼", "name_en": "", "sci": "Rhynchobatus australiae", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 59, "name": "南極星鯊", "name_en": "Gummy shark", "sci": "Mustelus antarcticus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 60, "name": "南極睡鯊", "name_en": "Southern sleeper shark", "sci": "Somniosus antarcticus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 61, "name": "南美星鯊", "name_en": "Speckled smooth-hound", "sci": "Mustelus mento", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 62, "name": "南部鳐鱼", "name_en": "southern stingray", "sci": "Dasyatis americana", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 63, "name": "南非單鰭電鰩", "name_en": "onefin electric ray", "sci": "Narke capensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 64, "name": "卡氏大西洋鳐", "name_en": "Spotback skate", "sci": "Atlantoraja castelnaui", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 65, "name": "卡氏尖頜烏鯊", "name_en": "viper dogfish", "sci": "Trigonognathus kabeyai", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 66, "name": "印尼長尾鬚鯊", "name_en": "Indonesian speckled carpetshark", "sci": "Hemiscyllium freycineti", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 67, "name": "印度後鰭錐齒鯊", "name_en": "Indian sand tiger", "sci": "Carcharias tricuspidatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 68, "name": "印度斑竹鲨", "name_en": "Slender bamboo shark", "sci": "Chiloscyllium indicum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 69, "name": "印度洋霞鯊", "name_en": "Ornate dogfish", "sci": "Centroscyllium ornatum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 70, "name": "印度蝠鱝", "name_en": "Bentfin devil ray", "sci": "Mobula thurstoni", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 71, "name": "卷盔鯊", "name_en": "roughskin spurdog", "sci": "Cirrhigaleus asper", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 72, "name": "叉頭燕魟", "name_en": "Flapnose ray", "sci": "Rhinoptera javanica", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 73, "name": "及达尖犁头鳐", "name_en": "giant guitarfish", "sci": "Rhynchobatus djiddensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 74, "name": "双吻前口蝠鲼", "name_en": "Giant oceanic manta ray", "sci": "Mobula birostris", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 75, "name": "双斑鳐", "name_en": "big skate", "sci": "Raja binoculata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 76, "name": "古巴角鯊", "name_en": "Cuban dogfish", "sci": "Squalus cubensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 77, "name": "古氏新魟", "name_en": "", "sci": "Neotrygon kuhlii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 78, "name": "台灣刺鯊", "name_en": "taiwan gulper shark", "sci": "Centrophorus niaukang", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 79, "name": "史氏深海鰩", "name_en": "", "sci": "Bathyraja smithii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 80, "name": "同齒刺鯊", "name_en": "little gulper shark", "sci": "Squalus uyato", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 81, "name": "后鳍尖吻银鲛", "name_en": "", "sci": "Harriotta raleighana", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 82, "name": "后鳍锯鳐", "name_en": "longcomb sawfish", "sci": "Pristis zijsron", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 83, "name": "吻斑蓝吻犁头鳐", "name_en": "Blackchin guitarfish", "sci": "Glaucostegus cemiculus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 84, "name": "哈氏刺鯊", "name_en": "", "sci": "Centrophorus harrissoni", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 85, "name": "哈氏原鯊", "name_en": "graceful catshark", "sci": "Proscyllium habereri", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 86, "name": "哈氏大尾扁魟", "name_en": "round stingray", "sci": "Urobatis halleri", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 87, "name": "哈氏斑竹鯊", "name_en": "Hasselt's bamboo shark", "sci": "Chiloscyllium hasseltii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 88, "name": "哈氏蓝吻犁头鳐", "name_en": "", "sci": "Glaucostegus halavi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 89, "name": "哈貝爾鯊", "name_en": "", "sci": "Carcharodon hubbelli", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 90, "name": "哈馬黑拉長尾鬚鯊", "name_en": "", "sci": "Hemiscyllium halmahera", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 91, "name": "喙吻田氏鯊", "name_en": "", "sci": "Deania calceus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 92, "name": "單鰭鰩屬", "name_en": "longtail skate", "sci": "Arhynchobatis asperrimus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 93, "name": "圆犁头鳐", "name_en": "bowmouth guitarfish", "sci": "Rhina ancylostoma", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 94, "name": "圓白鰩", "name_en": "", "sci": "Leucoraja circularis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 95, "name": "地中海電鱝", "name_en": "Atlantic torpedo", "sci": "Torpedo nobiliana", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 96, "name": "埃氏宽瓣鲨", "name_en": "Puffadder shyshark", "sci": "Haploblepharus edwardsii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 97, "name": "塔斯马尼亚澳洲双鳍电鳐", "name_en": "", "sci": "Narcine tasmaniensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 98, "name": "塔氏盲電鰩", "name_en": "", "sci": "Typhlonarke tarakea", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 99, "name": "塞氏犁头鳐", "name_en": "Goldeneye shovelnose ray", "sci": "Rhinobatos sainsburyi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 100, "name": "墨西哥乌鲨", "name_en": "Green lanternshark", "sci": "Etmopterus virens", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 101, "name": "墨西哥扁鲨", "name_en": "", "sci": "Squatina mexicana", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 102, "name": "墨西哥虎鯊", "name_en": "Mexican hornshark", "sci": "Heterodontus mexicanus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 103, "name": "多刺鳐", "name_en": "", "sci": "Raja polystigma", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 104, "name": "多眼齒鰩", "name_en": "Argus skate", "sci": "Dipturus polyommata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 105, "name": "大吻光尾鲨", "name_en": "flathead catshark", "sci": "Apristurus macrorhynchus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 106, "name": "大吻斜齿鲨", "name_en": "Pacific spadenose shark", "sci": "Scoliodon macrorhynchos", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 107, "name": "大燕魟", "name_en": "", "sci": "Gymnura altavela", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 108, "name": "大白鲨", "name_en": "great white shark", "sci": "Carcharodon carcharias", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 109, "name": "大眼六鳃鲨", "name_en": "bigeyed sixgill shark", "sci": "Hexanchus nakamurai", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 110, "name": "大眼真鲨", "name_en": "", "sci": "Carcharhinus macrops", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 111, "name": "大眼砂錐齒鯊", "name_en": "bigeye sand tiger", "sci": "Odontaspis noronhai", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 112, "name": "大眼角鯊", "name_en": "", "sci": "Squalus megalops", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 113, "name": "大眼长尾鲨", "name_en": "bigeye thresher", "sci": "Alopias superciliosus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 114, "name": "大西洋刺鯊", "name_en": "gulper shark", "sci": "Centrophorus granulosus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 115, "name": "大西洋副沙条鲨", "name_en": "Atlantic weasel shark", "sci": "Paragaleus pectoralis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 116, "name": "大西洋拟犁头鳐", "name_en": "", "sci": "Pseudobatos lentiginosus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 117, "name": "大西洋斜鋸牙鯊", "name_en": "Atlantic sharpnose shark", "sci": "Rhizoprionodon terraenovae", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 118, "name": "大西洋鋸尾鯊", "name_en": "Atlantic sawtail catshark", "sci": "Galeus atlanticus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 119, "name": "大西洋魟", "name_en": "Atlantic stingray", "sci": "Dasyatis sabina", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 120, "name": "大青鲨", "name_en": "", "sci": "Prionace glauca", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 121, "name": "大鼻穀鰩", "name_en": "", "sci": "Zearaja nasuta", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 122, "name": "大齒鋸鰩", "name_en": "large-tooth sawfish", "sci": "Pristis perotteti", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 123, "name": "天狗老板鯆", "name_en": "", "sci": "Dipturus tengu", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 124, "name": "太平洋斜鋸牙鯊", "name_en": "Pacific sharpnose shark", "sci": "Rhizoprionodon longurio", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 125, "name": "太平洋睡鯊", "name_en": "", "sci": "Somniosus pacificus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 126, "name": "太平洋窄尾𫚉", "name_en": "Pacific chupare", "sci": "Himantura pacifica", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 127, "name": "太平洋長鼻銀鮫", "name_en": "", "sci": "Rhinochimaera pacifica", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 128, "name": "太平洋鼠鯊", "name_en": "salmon shark", "sci": "Lamna ditropis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 129, "name": "头绒毛鲨", "name_en": "draughtsboard shark", "sci": "Cephaloscyllium isabellum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 130, "name": "奈氏魟", "name_en": "Blackish stingray", "sci": "Dasyatis navarrae", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 131, "name": "奥斯蒂诺鲨属", "name_en": "", "sci": "Ostenoselache stenosoma", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 132, "name": "奥氏江魟", "name_en": "", "sci": "Potamotrygon orbignyi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 133, "name": "奧氏兔銀鮫", "name_en": "", "sci": "Hydrolagus ogilbyi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 134, "name": "妆饰鬚鯊", "name_en": "ornate wobbegong", "sci": "Orectolobus ornatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 135, "name": "妖怪尖犁头鳐", "name_en": "", "sci": "Rhynchobatus mononoke", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 136, "name": "姥鲨", "name_en": "basking shark", "sci": "Cetorhinus maximus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 137, "name": "姬蝠鲼", "name_en": "devil fish", "sci": "Mobula mobular", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 138, "name": "威氏星鯊", "name_en": "White-fin smooth-hound", "sci": "Mustelus widodoi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 139, "name": "婆罗真鲨", "name_en": "Borneo shark", "sci": "Carcharhinus borneensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 140, "name": "安德森電鰩", "name_en": "Florida torpedo", "sci": "Torpedo andersoni", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 141, "name": "安格斯迪鲨", "name_en": "", "sci": "Carcharocles angustidens", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 143, "name": "安的列斯鋸尾鯊", "name_en": "Antilles catshark", "sci": "Galeus antillensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 144, "name": "宫齿鲛属", "name_en": "", "sci": "Delphyodontos dacriformes", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 145, "name": "宽尾拟角鲨", "name_en": "spined pygmy shark", "sci": "Squaliolus laticaudus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 146, "name": "宽尾斜齿鲨", "name_en": "Spadenose shark", "sci": "Scoliodon laticaudus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 147, "name": "宽纹虎鲨", "name_en": "Japanese bullhead shark", "sci": "Heterodontus japonicus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 148, "name": "宽鳍鲨", "name_en": "", "sci": "Lamiopsis temminckii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 149, "name": "密西西比软鳞铠鲨", "name_en": "American pocket shark", "sci": "Mollisquama mississippiensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 150, "name": "密點白鰩", "name_en": "", "sci": "Leucoraja ocellata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 151, "name": "寬鼻星鯊", "name_en": "starry smooth-hound", "sci": "Mustelus asterias", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 152, "name": "小乌鲨", "name_en": "smooth lanternshark", "sci": "Etmopterus pusillus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 153, "name": "小口异鳞鲨", "name_en": "Smallmouth velvet dogfish", "sci": "Scymnodon obscurus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 154, "name": "小口沙條鮫", "name_en": "sicklefin weasel shark", "sci": "Hemigaleus microstoma", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 155, "name": "小口雙鰭電鰩", "name_en": "Giant electric ray", "sci": "Narcine entemedor", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 156, "name": "小尾甕鰩", "name_en": "", "sci": "Okamejei leptoura", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 157, "name": "小尾真鲨", "name_en": "smalltail shark", "sci": "Carcharhinus porosus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 158, "name": "小星加州鰩", "name_en": "", "sci": "Raja stellulata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 159, "name": "小棘短鰩", "name_en": "", "sci": "Breviraja spinosa", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 160, "name": "小眼星鯊", "name_en": "Smalleye smooth-hound", "sci": "Mustelus higmani", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 161, "name": "小眼雙髻鯊", "name_en": "smalleye hammerhead", "sci": "Sphyrna tudes", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 162, "name": "小睛斑鰩", "name_en": "Smalleyed ray", "sci": "Raja microocellata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 163, "name": "小雙鰭電鰩", "name_en": "Lesser electric ray", "sci": "Narcine bancroftii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 164, "name": "小頭睡鯊", "name_en": "Greenland shark", "sci": "Somniosus microcephalus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 165, "name": "小鰭刺鯊", "name_en": "smallfin gulper shark", "sci": "Centrophorus moluccensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 166, "name": "小鰭睡鯊", "name_en": "Little sleeper shark", "sci": "Somniosus rostratus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 167, "name": "小齿锯鳐", "name_en": "common sawfish", "sci": "Pristis microdon", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 168, "name": "尖同鰭鰩", "name_en": "bignose fanskate", "sci": "Sympterygia acuta", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 169, "name": "尖吻七鳃鲨", "name_en": "sharpnose sevengill shark", "sci": "Heptranchias perlo", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 170, "name": "尖吻土魟", "name_en": "", "sci": "Dasyatis acutirostra", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 171, "name": "尖吻斜鋸牙鯊", "name_en": "", "sci": "Rhizoprionodon acutus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 172, "name": "尖吻角鯊", "name_en": "", "sci": "Squalus acutirostris", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 173, "name": "尖吻鲭鲨", "name_en": "shortfin mako shark", "sci": "Isurus oxyrinchus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 174, "name": "尖嘴魟", "name_en": "Pale-edged stingray", "sci": "Dasyatis zugei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 175, "name": "尖背角鯊", "name_en": "angular roughshark", "sci": "Oxynotus centrina", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 176, "name": "尖銳錐齒鯊", "name_en": "", "sci": "Carcharias cuspidatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 177, "name": "尖長吻鰩", "name_en": "", "sci": "Dipturus oxyrinchus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 178, "name": "尖鰭刺鯊", "name_en": "needle dogfish", "sci": "Centrophorus acus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 179, "name": "尖齒星鯊", "name_en": "Sharptooth smooth-hound", "sci": "Mustelus dorsalis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 180, "name": "尖齿异鳞鲨", "name_en": "Knifetooth dogfish", "sci": "Scymnodon ringens", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 181, "name": "巨口鲨", "name_en": "Megamouth shark", "sci": "Megachasma pelagios", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 182, "name": "巨齒鯊", "name_en": "megalodon", "sci": "Otodus megalodon", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 183, "name": "巴布亞長尾鬚鯊", "name_en": "Papuan epaulette shark", "sci": "Hemiscyllium hallstromi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 184, "name": "巴氏細鰩", "name_en": "Bigthorn skate", "sci": "Rajella barnardi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 185, "name": "巴西副江魟", "name_en": "", "sci": "Paratrygon aiereba", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 186, "name": "巴西大西洋鳐", "name_en": "Eyespot skate", "sci": "Atlantoraja cyclophora", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 187, "name": "巴西斜鋸牙鯊", "name_en": "Brazilian sharpnose shark", "sci": "Rhizoprionodon lalandii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 188, "name": "巴西达摩鲨", "name_en": "", "sci": "Isistius brasiliensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 189, "name": "巴西雙鰭電鰩", "name_en": "", "sci": "Narcine brasiliensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 190, "name": "布氏乌鲨", "name_en": "Lined lanternshark", "sci": "Etmopterus bullisi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 191, "name": "帆鰭尖背角鯊", "name_en": "Sailfin roughshark", "sci": "Oxynotus paradoxus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 192, "name": "希氏拟铠鲨", "name_en": "Sherwood dogfish", "sci": "Scymnodalatias sherwoodi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 193, "name": "希氏齒鰩", "name_en": "", "sci": "Dipturus healdi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 194, "name": "帝汶铲吻犁头鳐", "name_en": "spotted shovelnose ray", "sci": "Aptychotrema timorensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 195, "name": "帝王魟", "name_en": "", "sci": "Potamotrygon falkneri", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 196, "name": "带纹扁魟", "name_en": "", "sci": "Urolophus cruciatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 197, "name": "帶紋長鬚貓鯊", "name_en": "", "sci": "Poroderma africanum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 198, "name": "平滑真鲨", "name_en": "silky shark", "sci": "Carcharhinus falciformis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 199, "name": "平背鯆魮", "name_en": "Ocellate spot skate", "sci": "Okamejei kenojei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 200, "name": "廣鼻曲齒鮫", "name_en": "", "sci": "Loxodon macrorhinus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 201, "name": "弗氏鋸尾鯊", "name_en": "", "sci": "Galeus friedrichi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 202, "name": "弗氏鲼", "name_en": "", "sci": "Myliobatis freminvillei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 203, "name": "弧形長尾鯊", "name_en": "common thresher", "sci": "Alopias vulpinus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 204, "name": "忍者燈籠鯊", "name_en": "Ninja lanternshark", "sci": "Etmopterus benchleyi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 205, "name": "恆河露齒鯊", "name_en": "", "sci": "Glyphis gangeticus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 206, "name": "恩氏齒鰩", "name_en": "", "sci": "Dentiraja endeavouri", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 207, "name": "惠氏星鯊", "name_en": "Humpback smooth-hound", "sci": "Mustelus whitneyi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 208, "name": "懷特氏棘尾鰩", "name_en": "", "sci": "Spiniraja whitleyi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 209, "name": "戴氏扁鲨", "name_en": "", "sci": "Squatina david", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 210, "name": "扁吻光尾鲨", "name_en": "spatulasnout catshark", "sci": "Apristurus platyrhynchus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 211, "name": "扁头哈那鲨", "name_en": "broadnose sevengill shark", "sci": "Notorynchus cepedianus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 212, "name": "扁鯊", "name_en": "", "sci": "Squatina squatina", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 213, "name": "托氏魟", "name_en": "Tortonese's stingray", "sci": "Dasyatis tortonesei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 214, "name": "指鰩", "name_en": "", "sci": "Dactylobatus armatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 215, "name": "挪威長吻鰩", "name_en": "", "sci": "Dipturus nidarosiensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 216, "name": "擬團扇鰩", "name_en": "thornback guitarfish", "sci": "Platyrhinoidis triseriata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 217, "name": "擬皺唇鯊屬", "name_en": "false catshark", "sci": "Pseudotriakis microdon", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 218, "name": "斑点鼠鱼", "name_en": "spotted ratfish", "sci": "Hydrolagus colliei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 219, "name": "斑紋南犁頭鰩", "name_en": "", "sci": "Trygonorrhina fasciata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 220, "name": "斑纹犁头鳐", "name_en": "Ringstraked guitarfish", "sci": "Rhinobatos hynnicephalus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 221, "name": "斑纹须鲨", "name_en": "spotted wobbegong", "sci": "Orectolobus maculatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 222, "name": "斑鲨", "name_en": "Coral catshark", "sci": "Atelomycterus marmoratus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 223, "name": "斑鳍光唇鲨", "name_en": "Pygmy ribbontail catshark", "sci": "Eridacnis radcliffei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 224, "name": "斑點圓吻貓鯊", "name_en": "Australian spotted catshark", "sci": "Asymbolus analis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 225, "name": "斯普兰汀乌鲨", "name_en": "Splendid lanternshark", "sci": "Etmopterus splendidus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 226, "name": "斯氏深海鰩", "name_en": "", "sci": "Bathyraja smirnovi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 227, "name": "斯氏長尾鬚鯊", "name_en": "hooded carpetshark", "sci": "Hemiscyllium strahani", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 228, "name": "斯氏鰩", "name_en": "", "sci": "Raja straeleni", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 229, "name": "斯科比砂鰩", "name_en": "", "sci": "Psammobatis scobina", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 230, "name": "新月星鯊", "name_en": "Sicklefin smooth-hound", "sci": "Mustelus lunulatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 231, "name": "新西蘭星鯊", "name_en": "Spotted estuary smooth-hound", "sci": "Mustelus lenticulatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 232, "name": "无斑鹞鲼", "name_en": "Longheaded eagle ray", "sci": "Aetobatus flagellum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 233, "name": "无沟双髻鲨", "name_en": "great hammerhead", "sci": "Sphyrna mokarran", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 234, "name": "日光長吻鰩", "name_en": "", "sci": "Dipturus apricus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 235, "name": "日本尖背角鯊", "name_en": "Japanese roughshark", "sci": "Oxynotus japonicus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 236, "name": "日本扁鲨", "name_en": "", "sci": "Squatina japonica", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 237, "name": "日本橙黄鲨", "name_en": "saddle carpetshark", "sci": "Cirrhoscyllium japonicum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 238, "name": "日本燕魟", "name_en": "", "sci": "Gymnura japonica", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 239, "name": "日本蝠鲼", "name_en": "Spinetail mobula", "sci": "Mobula japanica", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 240, "name": "日本角鯊", "name_en": "Japanese spurdog", "sci": "Squalus japonicus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 241, "name": "日本锯尾鲨", "name_en": "Broadfin sawtail catshark", "sci": "Galeus nipponensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 242, "name": "日本锯鲨", "name_en": "Japanese sawshark", "sci": "Pristiophorus japonicus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 243, "name": "日本電鱝", "name_en": "Japanese sleeper ray", "sci": "Narke japonica", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 244, "name": "日本须鲨", "name_en": "Japanese wobbegong", "sci": "Orectolobus japonicus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 245, "name": "昆士兰锯鳐", "name_en": "dwarf sawfish", "sci": "Pristis clavata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 246, "name": "昆士蘭真鯊", "name_en": "Creek whaler", "sci": "Carcharhinus fitzroyensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 247, "name": "昆士蘭長吻鰩", "name_en": "", "sci": "Dipturus queenslandicus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 248, "name": "星云扁鲨", "name_en": "", "sci": "Squatina nebulosa", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 249, "name": "星斑鰩", "name_en": "", "sci": "Raja asterias", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 250, "name": "星鯊", "name_en": "common smooth-hound", "sci": "Mustelus mustelus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 251, "name": "普氏拟犁头鳐", "name_en": "", "sci": "Pseudobatos prahli", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 252, "name": "普通電鰩", "name_en": "common torpedo", "sci": "Torpedo torpedo", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 253, "name": "晴斑長吻鰩", "name_en": "Slimeskate", "sci": "Dipturus pullopunctatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 254, "name": "晶吻鰩", "name_en": "Clearnose skate", "sci": "Raja eglanteria", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 255, "name": "智利深海鰩", "name_en": "", "sci": "Bathyraja magellanica", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 256, "name": "朝鮮鰩屬", "name_en": "", "sci": "Hongeo koreana", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 257, "name": "杜氏南犁頭鰩", "name_en": "", "sci": "Trygonorrhina dumerilii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 258, "name": "杜氏扁鲨", "name_en": "", "sci": "Squatina dumeril", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 259, "name": "杜氏真鲨", "name_en": "Whitecheek shark", "sci": "Carcharhinus dussumieri", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 260, "name": "条纹斑竹鲨", "name_en": "Whitespotted bamboo shark", "sci": "Chiloscyllium plagiosum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 261, "name": "枪头真鲨", "name_en": "hardnose shark", "sci": "Carcharhinus macloti", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 262, "name": "柠檬鲨", "name_en": "", "sci": "Negaprion brevirostris", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 263, "name": "查菲窄尾魟", "name_en": "Giant freshwater stingray", "sci": "Himantura polylepis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 264, "name": "查菲窄尾𫚉", "name_en": "", "sci": "Himantura chaophraya", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 265, "name": "格氏長吻鰩", "name_en": "", "sci": "Dipturus grahami", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 266, "name": "棘尾深海鰩", "name_en": "", "sci": "Bathyraja spinicauda", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 267, "name": "棘深海鰩", "name_en": "Pacific white skate", "sci": "Bathyraja spinosissima", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 268, "name": "棘背鈍頭鳐", "name_en": "Thorny skate", "sci": "Amblyraja radiata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 269, "name": "棘鯊", "name_en": "bramble shark", "sci": "Echinorhinus brucus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 270, "name": "棘鳞乌鲨", "name_en": "Great lanternshark", "sci": "Etmopterus princeps", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 271, "name": "模拉里乌鲨", "name_en": "Slendertail lanternshark", "sci": "Etmopterus molleri", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 272, "name": "横纹前鳍鲼", "name_en": "", "sci": "Pteromylaeus bovinus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 273, "name": "櫛齒鋸鰩", "name_en": "smalltooth sawfish", "sci": "Pristis pectinata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 274, "name": "欧氏尖吻鲛", "name_en": "goblin shark", "sci": "Mitsukurina owstoni", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 275, "name": "欧氏荆鲨", "name_en": "", "sci": "Centroscymnus owstonii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 276, "name": "欧氏鳐", "name_en": "", "sci": "Dipturus olseni", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 277, "name": "比氏燈籠棘鮫", "name_en": "Blurred lanternshark", "sci": "Etmopterus bigelowi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 278, "name": "沃氏鬚鯊", "name_en": "northern wobbegong", "sci": "Orectolobus wardi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 279, "name": "沙拉真鲨", "name_en": "", "sci": "Carcharhinus sorrah", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 280, "name": "沙氏锯尾鲨", "name_en": "Blacktip sawtail catshark", "sci": "Galeus sauteri", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 281, "name": "沙虎鯊", "name_en": "sand tiger shark", "sci": "Carcharias taurus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 282, "name": "法氏細鰩", "name_en": "", "sci": "Rajella fyllae", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 283, "name": "波氏同鰭鰩", "name_en": "smallnose fanskate", "sci": "Sympterygia bonapartii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 284, "name": "波氏環鰩", "name_en": "", "sci": "Okamejei powelli", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 285, "name": "波氏鹞鲼", "name_en": "", "sci": "Aetobatus poeyi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 286, "name": "波缘窄尾魟", "name_en": "honeycomb whipray", "sci": "Himantura undulata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 287, "name": "波鰩", "name_en": "Undulate ray", "sci": "Raja undulata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 288, "name": "泰勒斜鋸牙鯊", "name_en": "Australian sharpnose shark", "sci": "Rhizoprionodon taylori", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 289, "name": "泰魯魟", "name_en": "", "sci": "Potamotrygon castexi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 290, "name": "洁背强鳍鳐", "name_en": "banded guitarfish", "sci": "Zapteryx exasperata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 291, "name": "浅海长尾鲨", "name_en": "pelagic thresher", "sci": "Alopias pelagicus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 292, "name": "淡黑新鰩", "name_en": "", "sci": "Neoraja caerulea", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 293, "name": "深棕雙鰭電鰩", "name_en": "", "sci": "Narcine brunnea", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 294, "name": "深水侏鰩", "name_en": "", "sci": "Fenestraja plutonia", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 295, "name": "深水田氏鯊", "name_en": "Arrowhead dogfish", "sci": "Deania profundorum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 296, "name": "深水長吻鰩", "name_en": "", "sci": "Dipturus acrobelus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 297, "name": "深海电鳐", "name_en": "", "sci": "Benthobatis moresbyi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 298, "name": "湯氏黃點鯆", "name_en": "", "sci": "Platyrhina tangi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 299, "name": "澳大利亞虎鯊", "name_en": "Port Jackson shark", "sci": "Heterodontus portusjacksoni", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 300, "name": "澳洲尖背角鯊", "name_en": "Prickly dogfish", "sci": "Oxynotus bruniensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 301, "name": "澳洲真鲨", "name_en": "nervous shark", "sci": "Carcharhinus cautus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 302, "name": "澳洲睡電鰩", "name_en": "coffin ray", "sci": "Hypnos monopterygius", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 303, "name": "澳洲绒毛鲨", "name_en": "Australian swellshark", "sci": "Cephaloscyllium laticeps", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 304, "name": "澳洲铲吻犁头鳐", "name_en": "southern shovelnose ray", "sci": "Aptychotrema vincentiana", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 305, "name": "灰三齿鲨", "name_en": "Whitetip reef shark", "sci": "Triaenodon obesus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 306, "name": "灰六鳃鲨", "name_en": "Nomititis lovulitos", "sci": "Hexanchus griseus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 307, "name": "灰斑弧犁头鳐", "name_en": "", "sci": "Acroteriobatus leucospilus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 308, "name": "灰斑竹鲨", "name_en": "Grey bamboo shark", "sci": "Chiloscyllium griseum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 309, "name": "灰星鲨", "name_en": "", "sci": "Mustelus griseus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 310, "name": "灰色真鲨", "name_en": "Dusky shark", "sci": "Carcharhinus obscurus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 311, "name": "灰長吻鰩", "name_en": "", "sci": "Dipturus canutus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 312, "name": "炎亭尖犁头鳐", "name_en": "smoothnose wedgefish", "sci": "Rhynchobatus laevis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 313, "name": "点纹斑竹鲨", "name_en": "Brownbanded bamboo shark", "sci": "Chiloscyllium punctatum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 314, "name": "烏翅真鯊", "name_en": "Blacktip reef shark", "sci": "Carcharhinus melanopterus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 315, "name": "爪哇真鲨", "name_en": "", "sci": "Carcharhinus tjutjot", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 316, "name": "牛魟", "name_en": "", "sci": "Dasyatis ushiei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 317, "name": "牛鼻鳐", "name_en": "Cownose ray", "sci": "Rhinoptera bonasus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 318, "name": "犁鰭檸檬鮫", "name_en": "sicklefin lemon shark", "sci": "Negaprion acutidens", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 319, "name": "狭纹虎鲨", "name_en": "zebra bullhead shark", "sci": "Heterodontus zebra", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 320, "name": "獅色窄尾魟", "name_en": "Leopard whipray", "sci": "Himantura leoparda", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 321, "name": "环吻犁头鳐", "name_en": "", "sci": "Pseudobatos productus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 322, "name": "珊瑚礁鬼蝠魟", "name_en": "reef manta ray", "sci": "Manta alfredi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 323, "name": "珍珠魟", "name_en": "ocellate river stingray", "sci": "Potamotrygon motoro", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 324, "name": "琴犁頭鰩", "name_en": "Common guitarfish", "sci": "Rhinobatos rhinobatos", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 325, "name": "瓜氏虎鯊", "name_en": "Galapagos bullhead shark", "sci": "Heterodontus quoyi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 326, "name": "瓦氏長鬚鯊", "name_en": "blind shark", "sci": "Brachaelurus waddi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 327, "name": "異鱗鮫", "name_en": "Velvet dogfish", "sci": "Zameus squamulosus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 328, "name": "疣突扁鲨", "name_en": "", "sci": "Squatina aculeata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 329, "name": "疣背鬚鯊", "name_en": "cobbler wobbegong", "sci": "Sutorectus tentaculatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 330, "name": "白令海深海鰩", "name_en": "", "sci": "Bathyraja interrupta", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 331, "name": "白印霞鯊", "name_en": "Combtooth dogfish", "sci": "Centroscyllium nigrum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 332, "name": "白吻鰩", "name_en": "bottlenose skate", "sci": "Rostroraja alba", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 333, "name": "白斑宽瓣鲨", "name_en": "Dark shyshark", "sci": "Haploblepharus pictus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 334, "name": "白斑星鲨", "name_en": "", "sci": "Mustelus manazo", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 335, "name": "白斑深海鰩", "name_en": "White-dotted skate", "sci": "Bathyraja albomaculata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 336, "name": "白斑細鰩", "name_en": "", "sci": "Rajella lintea", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 337, "name": "白斑角鯊", "name_en": "spiny dogfish shark", "sci": "Squalus acanthias", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 338, "name": "白点拟犁头鳐", "name_en": "", "sci": "Pseudobatos percellens", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 339, "name": "白边小鳍鲨", "name_en": "pygmy shark", "sci": "Euprotomicrus bispinatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 340, "name": "白邊真鯊", "name_en": "", "sci": "Carcharhinus albimarginatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 341, "name": "白邊霞鯊", "name_en": "Whitefin dogfish", "sci": "Centroscyllium ritteri", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 342, "name": "白黑深海鰩", "name_en": "", "sci": "Bathyraja leucomelanos", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 343, "name": "白點虎鯊", "name_en": "whitespotted bullhead shark", "sci": "Heterodontus ramalheira", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 344, "name": "白點貓鯊", "name_en": "Izu catshark", "sci": "Scyliorhinus tokubee", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 345, "name": "皱唇鲨", "name_en": "banded houndshark", "sci": "Triakis scyllium", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 346, "name": "皺肢鰩", "name_en": "", "sci": "Cruriraja rugosa", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 347, "name": "皺鰓鯊", "name_en": "", "sci": "Chlamydoselachus anguineus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 348, "name": "盤臀電鰩", "name_en": "apron ray", "sci": "Discopyge tschudii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 349, "name": "盾尾鯊", "name_en": "Salamander shark", "sci": "Parmaturus pilosus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 350, "name": "眶嵴虎鯊", "name_en": "crested bullhead shark", "sci": "Heterodontus galeatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 351, "name": "眼斑鷂鱝", "name_en": "", "sci": "Aetobatus ocellatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 352, "name": "眼斑齒鰩", "name_en": "", "sci": "Dipturus oculus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 353, "name": "瞬眼尖犁头鳐", "name_en": "", "sci": "Rhynchobatus palpebratus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 354, "name": "短吻双髻鲨", "name_en": "", "sci": "Sphyrna media", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 355, "name": "短吻强鳍鳐", "name_en": "shortnose guitarfish", "sci": "Zapteryx brevirostris", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 356, "name": "短吻角鲨", "name_en": "", "sci": "Squalus brevirostris", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 357, "name": "短吻鋸鯊", "name_en": "shortnose sawshark", "sci": "Pristiophorus nudipinnis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 358, "name": "短尾刺魟", "name_en": "short-tail stingray", "sci": "Dasyatis brevicaudata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 359, "name": "短尾同鰭鰩", "name_en": "", "sci": "Sympterygia brevicaudata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 360, "name": "短尾江魟", "name_en": "", "sci": "Potamotrygon brachyura", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 361, "name": "短尾烏鮫", "name_en": "Short-tail lanternshark", "sci": "Etmopterus brachyurus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 362, "name": "短尾真鲨", "name_en": "", "sci": "Carcharhinus brachyurus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 363, "name": "短尾護士鯊", "name_en": "short-tail nurse shark", "sci": "Pseudoginglymostoma brevicaudatum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 364, "name": "短尾鰩", "name_en": "", "sci": "Raja brachyura", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 365, "name": "短棘鲨", "name_en": "hooktooth dogfish", "sci": "Aculeola nigra", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 366, "name": "短翅蝠鲼", "name_en": "", "sci": "Mobula kuhlii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 367, "name": "短鳍斜锯牙鲨", "name_en": "Grey sharpnose shark", "sci": "Rhizoprionodon oligolinx", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 368, "name": "石山氏侏鰩", "name_en": "", "sci": "Fenestraja ishiyamai", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 369, "name": "石紋電鰩", "name_en": "Marbled electric ray", "sci": "Torpedo marmorata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 370, "name": "科氏真鲨", "name_en": "", "sci": "Carcharhinus coatesi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 371, "name": "科氏長鬚鯊", "name_en": "", "sci": "Brachaelurus colcloughi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 372, "name": "稀棘深海鰩", "name_en": "Deepsea skate", "sci": "Bathyraja abyssicola", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 373, "name": "突吻弧犁头鳐", "name_en": "", "sci": "Acroteriobatus annulatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 374, "name": "窄吻鯊屬", "name_en": "", "sci": "Nasolamia velox", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 375, "name": "窄头双髻鲨", "name_en": "bonnethead", "sci": "Sphyrna tiburo", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 376, "name": "窄鼻拟犁头鳐", "name_en": "", "sci": "Pseudobatos buthi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 377, "name": "笠鱗鮫", "name_en": "prickly shark", "sci": "Echinorhinus cookei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 378, "name": "箕作氏兔銀鮫", "name_en": "", "sci": "Hydrolagus mitsukurii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 380, "name": "粗体光尾鲨", "name_en": "", "sci": "Apristurus pinguis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 381, "name": "粗吻田氏鯊", "name_en": "Rough longnose dogfish", "sci": "Deania hystricosa", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 382, "name": "粗尾鋸尾鯊", "name_en": "Roughtail catshark", "sci": "Galeus arae", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 383, "name": "粗背鰩", "name_en": "", "sci": "Raja radula", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 384, "name": "糙前鳍鲼", "name_en": "", "sci": "Pteromylaeus asperrimus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 385, "name": "糙沙粒𫚉", "name_en": "porcupine ray", "sci": "Urogymnus asperrimus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 386, "name": "糙皮長吻鰩", "name_en": "", "sci": "Dipturus trachyderma", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 387, "name": "糙網鰩", "name_en": "Smooth deep-sea skate", "sci": "Brochiraja asperula", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 388, "name": "糙齿鲨", "name_en": "crocodile shark", "sci": "Pseudocarcharias kamoharai", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 389, "name": "約氏長吻鰩", "name_en": "", "sci": "Dipturus johannisdavisi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 390, "name": "素氏藍吻犁頭鰩", "name_en": "Clubnose guitarfish", "sci": "Glaucostegus thouin", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 391, "name": "索科特拉弧犁头鳐", "name_en": "", "sci": "Acroteriobatus stehmanni", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 392, "name": "紫紅醜鰩", "name_en": "", "sci": "Malacoraja senta", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 393, "name": "紫背大西洋鳐", "name_en": "La Plata skate", "sci": "Atlantoraja platana", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 394, "name": "紫色翼魟", "name_en": "pelagic stingray", "sci": "Pteroplatytrygon violacea", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 395, "name": "細線鬚鯊", "name_en": "", "sci": "Orectolobus leptolineatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 396, "name": "細鋸尾鯊", "name_en": "Slender sawtail catshark", "sci": "Galeus gracilis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 397, "name": "細鬚雅鯊", "name_en": "barbeled houndshark", "sci": "Leptocharias smithii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 398, "name": "細點窄尾魟", "name_en": "Mangrove whipray", "sci": "Himantura granulata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 399, "name": "結刺白鰩", "name_en": "Shagreen ray", "sci": "Leucoraja fullonica", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 400, "name": "絨鯊屬", "name_en": "", "sci": "Centroselachus crepidater", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 401, "name": "纳氏鹞鲼", "name_en": "spotted eagle ray", "sci": "Aetobatus narinari", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 402, "name": "缺鰭電鰩", "name_en": "", "sci": "Temera hardwickii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 403, "name": "罗切氏蝠鲼", "name_en": "", "sci": "Mobula rochebrunei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 404, "name": "罗宾斯氏乌鲨", "name_en": "West Indian lanternshark", "sci": "Etmopterus robinsi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 405, "name": "美星鯊", "name_en": "dusky smooth-hound", "sci": "Mustelus canis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 406, "name": "美洲吻鰩", "name_en": "", "sci": "Raja texana", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 407, "name": "美鳐", "name_en": "Mottled skate", "sci": "Raja pulchra", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 408, "name": "翅鯊", "name_en": "", "sci": "Galeorhinus galeus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 409, "name": "老挝魟", "name_en": "Mekong freshwater stingray", "sci": "Dasyatis laosensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 410, "name": "聂氏无刺鲼", "name_en": "Banded eagle ray", "sci": "Aetomylaeus nichofii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 411, "name": "肖氏梳板鳐", "name_en": "striped panray", "sci": "Zanobatus schoenleinii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 412, "name": "肩斑白鰩", "name_en": "", "sci": "Leucoraja naevus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 413, "name": "肩章鯊", "name_en": "epaulette shark", "sci": "Hemiscyllium ocellatum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 414, "name": "背斑雙電鰩", "name_en": "Bullseye electric ray", "sci": "Diplobatis ommata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 415, "name": "背棘鰩", "name_en": "thornback ray", "sci": "Raja clavata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 416, "name": "腔鳞荆鲨", "name_en": "Portuguese dogfish", "sci": "Centroscymnus coelolepis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 417, "name": "腹斑深海鰩", "name_en": "Aleutian skate", "sci": "Bathyraja aleutica", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 418, "name": "舌形双鳍电鳐", "name_en": "", "sci": "Narcine lingula", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 419, "name": "舒氏乌鲨", "name_en": "Fringefin lanternshark", "sci": "Etmopterus schultzi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 420, "name": "舒氏星鯊", "name_en": "Narrownose smooth-hound", "sci": "Mustelus schmitti", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 421, "name": "艾傑深海鰩", "name_en": "Aguja skate", "sci": "Bathyraja aguja", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 422, "name": "艾氏盲電鰩", "name_en": "blind electric ray", "sci": "Typhlonarke aysoni", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 423, "name": "芒基蝠鱝", "name_en": "", "sci": "Mobula munkiana", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 424, "name": "花尾燕魟", "name_en": "Longtail butterfly ray", "sci": "Gymnura poecilura", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 425, "name": "花点无刺鲼", "name_en": "Mottled eagle ray", "sci": "Aetomylaeus maculatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 426, "name": "花点窄尾魟", "name_en": "reticulate whipray", "sci": "Himantura uarnak", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 427, "name": "花鬚鯊", "name_en": "floral banded wobbegong", "sci": "Orectolobus floridus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 428, "name": "菱魟", "name_en": "Diamond Stingray", "sci": "Dasyatis dipterura", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 429, "name": "萊氏齒鰩", "name_en": "thornback skate", "sci": "Dentiraja lemprieri", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 430, "name": "葉吻無鰭鰩", "name_en": "", "sci": "Anacanthobatis folirostris", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 431, "name": "葉鬚鯊", "name_en": "", "sci": "Eucrossorhinus dasypogon", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 432, "name": "葉鱗刺鯊", "name_en": "leafscale gulper shark", "sci": "Centrophorus squamosus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 433, "name": "蒂氏真鲨", "name_en": "Australian blacktip shark", "sci": "Carcharhinus tilstoni", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 434, "name": "蒙式角鯊", "name_en": "", "sci": "Squalus montalbani", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 435, "name": "蒙氏翼柱頭鯊", "name_en": "", "sci": "Ptychodus mortoni", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 436, "name": "蒙鰩", "name_en": "", "sci": "Raja montagui", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 437, "name": "蒲原氏霞鯊", "name_en": "Bareskin dogfish", "sci": "Centroscyllium kamoharai", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 438, "name": "蓝吻犁头鳐", "name_en": "Common shovelnose ray", "sci": "Glaucostegus typus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 439, "name": "蓝纹魟", "name_en": "common stingray", "sci": "Dasyatis pastinaca", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 440, "name": "蔷薇真鲨", "name_en": "", "sci": "Carcharhinus brevipinna", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 441, "name": "薄鰩", "name_en": "", "sci": "Insentiraja subtilispinosa", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 442, "name": "薛氏犁头鳐", "name_en": "", "sci": "Rhinobatos schlegelii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 443, "name": "薩式角鯊", "name_en": "", "sci": "Squalus suckleyi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 444, "name": "藍斑條尾魟", "name_en": "bluespotted ribbontail ray", "sci": "Taeniura lymma", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 445, "name": "藍灰隆背鰩", "name_en": "", "sci": "Notoraja azurea", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 446, "name": "藍長吻鰩", "name_en": "common skate", "sci": "Dipturus batis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 447, "name": "虎纹梅花鲨", "name_en": "Tiger catshark", "sci": "Halaelurus natalensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 448, "name": "虎纹猫鲨", "name_en": "cloudy catshark", "sci": "Scyliorhinus torazame", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 449, "name": "蝟白鰩", "name_en": "Little skate", "sci": "Leucoraja erinacea", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 450, "name": "蝠状无刺鲼", "name_en": "Ornate eagle ray", "sci": "Aetomylaeus vespertilio", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 451, "name": "褐圓吻貓鯊", "name_en": "Gulf catshark", "sci": "Asymbolus vincenti", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 452, "name": "褐星鯊", "name_en": "brown smooth-hound", "sci": "Mustelus henlei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 453, "name": "褐背蝠鱝", "name_en": "Box ray", "sci": "Mobula tarapacana", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 454, "name": "褐黃齒鰩", "name_en": "", "sci": "Dipturus cerva", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 455, "name": "褐黄扁魟", "name_en": "Sepia stingray", "sci": "Urolophus aurantiacus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 456, "name": "褶尾萝卜𫚉", "name_en": "cowtail stingray", "sci": "Pastinachus sephen", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 457, "name": "西氏真鲨", "name_en": "", "sci": "Carcharhinus sealei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 458, "name": "西澳鬚鯊", "name_en": "western wobbegong", "sci": "Orectolobus hutchinsi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 459, "name": "西非鋸尾鯊", "name_en": "African sawtail catshark", "sci": "Galeus polli", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 460, "name": "諾氏星鯊", "name_en": "Narrowfin smooth-hound", "sci": "Mustelus norrisi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 461, "name": "豹纹鲨", "name_en": "zebra shark", "sci": "Stegostoma fasciatum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 462, "name": "豹鮫", "name_en": "Blackspotted catshark", "sci": "Halaelurus buergeri", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 463, "name": "費氏大電鱝", "name_en": "New Zealand torpedo", "sci": "Torpedo fairchildi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 465, "name": "赤魟", "name_en": "", "sci": "Hemitrygon akajei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 466, "name": "赫尔须鲨", "name_en": "gulf wobbegong", "sci": "Orectolobus halei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 467, "name": "路氏雙髻鯊", "name_en": "scalloped hammerhead", "sci": "Sphyrna lewini", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 468, "name": "达氏近𫚉", "name_en": "deepwater stingray", "sci": "Plesiobatis daviesi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 469, "name": "里氏深海鰩", "name_en": "Richardson's ray", "sci": "Bathyraja richardsoni", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 470, "name": "里約鰩屬", "name_en": "Rio skate", "sci": "Rioraja agassizii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 471, "name": "金魟", "name_en": "blue stingray", "sci": "Dasyatis chrysonota", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 472, "name": "金點魟", "name_en": "Bigtooth river stingray", "sci": "Potamotrygon henlei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 473, "name": "鈍吻真鯊", "name_en": "", "sci": "Carcharhinus amblyrhynchoides", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 474, "name": "鉸口鯊", "name_en": "nurse shark", "sci": "Ginglymostoma cirratum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 475, "name": "鋸鰩", "name_en": "largetooth sawfish", "sci": "Pristis pristis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 476, "name": "鋸齒刺鯊", "name_en": "mosaic gulper shark", "sci": "Centrophorus tessellatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 477, "name": "鏟砂鰩", "name_en": "", "sci": "Psammobatis rutrum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 478, "name": "鏡鰩", "name_en": "", "sci": "Raja miraletus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 479, "name": "钝头𫚉", "name_en": "Bluntnose stingray", "sci": "Dasyatis say", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 480, "name": "钝锯鳐", "name_en": "", "sci": "Anoxypristis cuspidata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 481, "name": "钩鼻铲吻犁头鳐", "name_en": "Eastern shovelnose ray", "sci": "Aptychotrema rostrata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 482, "name": "铠鲨", "name_en": "", "sci": "Dalatias licha", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 483, "name": "锤头双髻鲨", "name_en": "smooth hammerhead", "sci": "Sphyrna zygaena", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 484, "name": "長吻真鯊", "name_en": "Night shark", "sci": "Carcharhinus signatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 485, "name": "長吻角鯊", "name_en": "Shortspine spurdog", "sci": "Squalus mitsukurii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 486, "name": "長孔真鯊", "name_en": "Finetooth shark", "sci": "Carcharhinus isodon", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 487, "name": "長尾霞鯊", "name_en": "Granular dogfish", "sci": "Centroscyllium granulatum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 488, "name": "長鬚棘鮫", "name_en": "mandarin dogfish", "sci": "Cirrhigaleus barbifer", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 489, "name": "長鰭鋸尾鯊", "name_en": "longfin sawtail catshark", "sci": "Galeus cadenati", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 490, "name": "長鰭鯖鯊", "name_en": "longfin mako shark", "sci": "Isurus paucus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 491, "name": "長鼻白鰩", "name_en": "", "sci": "Leucoraja longirostris", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 492, "name": "长吻双髻鲨", "name_en": "scalloped bonnethead", "sci": "Sphyrna corona", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 493, "name": "长吻锯鲨", "name_en": "", "sci": "Pristiophorus cirratus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 494, "name": "长吻鳐", "name_en": "", "sci": "Raja rhina", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 495, "name": "长头光尾鲨", "name_en": "Longhead catshark", "sci": "Apristurus longicephalus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 496, "name": "长鳍真鲨", "name_en": "oceanic whitetip shark", "sci": "Carcharhinus longimanus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 497, "name": "长齿楔齿鲨", "name_en": "", "sci": "Sphenodus longidens", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 498, "name": "阴影绒毛鲨", "name_en": "Blotchy swell shark", "sci": "Cephaloscyllium umbratile", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 499, "name": "阿拉伯斑竹鯊", "name_en": "Arabian carpetshark", "sci": "Chiloscyllium arabicum", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 500, "name": "阿拉伯星鯊", "name_en": "Arabian smooth-hound", "sci": "Mustelus mosis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 501, "name": "阿氏甕鰩", "name_en": "", "sci": "Okamejei arafurensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 502, "name": "雀斑白鰩", "name_en": "", "sci": "Leucoraja lentiginosa", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 503, "name": "雙翅單鰭電鰩", "name_en": "numbray", "sci": "Narke dipterygia", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 504, "name": "雜紋灰鮫", "name_en": "ocellate topeshark", "sci": "Hemitriakis complicofasciata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 505, "name": "霍氏拟犁头鳐", "name_en": "", "sci": "Pseudobatos horkelii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 506, "name": "露齒鯊", "name_en": "", "sci": "Glyphis glyphis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 507, "name": "非洲扁鲨", "name_en": "", "sci": "Squatina africana", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 508, "name": "非洲长吻银鲛", "name_en": "", "sci": "Rhinochimaera africana", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 509, "name": "韋氏圓鰩", "name_en": "", "sci": "Irolita waitii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 510, "name": "項斑長尾鬚鯊", "name_en": "speckled carpetshark", "sci": "Hemiscyllium trispeculare", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 511, "name": "顆粒犁头鳐", "name_en": "", "sci": "Glaucostegus granulatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 512, "name": "馬德拉鰩", "name_en": "", "sci": "Raja maderensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 513, "name": "馬歇爾虎鯊", "name_en": "", "sci": "Heterodontus marshallae", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 514, "name": "馬氏深海電鰩", "name_en": "", "sci": "Benthobatis marcida", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 515, "name": "马尔加什弧犁头鳐", "name_en": "", "sci": "Acroteriobatus andysabini", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 516, "name": "马氏江魟", "name_en": "", "sci": "Potamotrygon magdalenae", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 517, "name": "高翅真鯊", "name_en": "", "sci": "Carcharhinus altimus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 518, "name": "高鳍真鲨", "name_en": "sandbar shark", "sci": "Carcharhinus plumbeus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 519, "name": "高鳍真鲨", "name_en": "", "sci": "Carcharhinus amboinensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 520, "name": "鬼魟", "name_en": "Broad stingray", "sci": "Dasyatis lata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 521, "name": "魔電鰩", "name_en": "Leopard torpedo", "sci": "Torpedo panthera", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 522, "name": "鯨鯊", "name_en": "whale shark", "sci": "Rhincodon typus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 523, "name": "鲍氏沙条鲨", "name_en": "Hooktooth shark", "sci": "Chaenogaleus macrostoma", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 524, "name": "鳶齒鰩", "name_en": "", "sci": "Dentiraja confusa", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 525, "name": "鸢鲼", "name_en": "", "sci": "Myliobatis tobijei", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 526, "name": "鹰状无刺鲼", "name_en": "", "sci": "Aetomylaeus milvus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 527, "name": "麥克電鰩", "name_en": "", "sci": "Torpedo mackayana", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 528, "name": "麦氏电鳐", "name_en": "", "sci": "Torpedo macneilli", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 529, "name": "黃土魟", "name_en": "", "sci": "Dasyatis bennettii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 530, "name": "黃斑深海鰩", "name_en": "", "sci": "Bathyraja mariposa", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 531, "name": "黄鳐鱼", "name_en": "Yellow stingray", "sci": "Urobatis jamaicensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 532, "name": "黏同鰭鰩", "name_en": "filetail fanskate", "sci": "Sympterygia lima", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 533, "name": "黑口鋸尾鯊", "name_en": "blackmouth catshark", "sci": "Galeus melastomus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 534, "name": "黑吻真鲨", "name_en": "blacknose shark", "sci": "Carcharhinus acronotus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 535, "name": "黑尾真鲨", "name_en": "Grey reef shark", "sci": "Carcharhinus amblyrhynchos", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 536, "name": "黑尾角鯊", "name_en": "Blacktailed spurdog", "sci": "Squalus melanurus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 537, "name": "黑斑双鳍电鳐", "name_en": "", "sci": "Narcine maculata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 538, "name": "黑斑星鯊", "name_en": "Blackspotted smooth-hound", "sci": "Mustelus punctulatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 539, "name": "黑斑条尾魟", "name_en": "round ribbontail ray", "sci": "Taeniura meyeni", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 540, "name": "黑斑電鰩", "name_en": "blackspotted torpedo", "sci": "Torpedo fuscomaculata", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 541, "name": "黑白魟", "name_en": "Xingu River ray", "sci": "Potamotrygon leopoldi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 542, "name": "黑緣刺鯊", "name_en": "dwarf gulper shark", "sci": "Centrophorus atromarginatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 543, "name": "黑线银鲛", "name_en": "", "sci": "Chimaera phantasma", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 544, "name": "黑腹烏鯊", "name_en": "velvet belly lanternshark", "sci": "Etmopterus spinax", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 545, "name": "黑邊鰭真鯊", "name_en": "blacktip shark", "sci": "Carcharhinus limbatus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 546, "name": "黑霞鯊", "name_en": "Black dogfish", "sci": "Centroscyllium fabricii", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 547, "name": "黑鳍下盔鲨", "name_en": "Blacktip tope", "sci": "Hypogaleus hyugaensis", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 548, "name": "黑鳍基齿鲨", "name_en": "Pondicherry shark", "sci": "Carcharhinus hemiodon", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 549, "name": "黑點長吻鰩", "name_en": "", "sci": "Dipturus melanospilus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 550, "name": "默氏深海鰩", "name_en": "", "sci": "Bathyraja murrayi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 551, "name": "鼠鲨", "name_en": "porbeagle", "sci": "Lamna nasus", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 552, "name": "齐氏窄尾魟", "name_en": "Whitespotted whipray", "sci": "Himantura gerrardi", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 553, "name": "日本翅鲨", "name_en": "", "sci": "Hemitriakis japanica", "family": "", "family_en": "", "order": "", "order_en": ""},
{"id": 554, "name": "枪型泛鲭鲨", "name_en": "", "sci": "Carcharodon hastalis", "family": "", "family_en": "", "order": "", "order_en": ""}
];
