/* 1001 种软骨鱼 — 上线数据集（244 条，均有真实照片）
   由 build_shipped.py 从母版 shark.full.js 生成。母版共 554 条。 */
window.SHARK_DATA = [
{"id": 1, "name": "丁字双髻鲨", "sci": "Eusphyra blochii", "family": "双髻鲨科", "family_en": "Sphyrnidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "CR", "cat": "shark"},
{"id": 3, "name": "丁氏双鳍电鳐", "name_en": "Blackspotted numbfish", "sci": "Narcine timlei", "family": "双鳍电鳐科", "family_en": "Narcinidae", "order": "电鳐目", "order_en": "Torpediniformes", "iucn": "VU", "cat": "ray"},
{"id": 4, "name": "丘布特凯克鲨", "name_en": "Carcharocles chubutensis", "sci": "Carcharodon subauriculatus", "family": "鼠鲨科", "family_en": "Lamnidae", "order": "鼠鲨目", "order_en": "Lamniformes", "cat": "shark"},
{"id": 5, "name": "东京电鳐", "sci": "Torpedo tokionis", "family": "电鳐科", "family_en": "Torpedinidae", "order": "电鳐目", "order_en": "Torpediniformes", "cat": "ray"},
{"id": 6, "name": "东太平洋绒毛鲨", "name_en": "swellshark", "sci": "Cephaloscyllium ventriosum", "family": "猫鲨科", "family_en": "Scyliorhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 7, "name": "中华光尾鲨", "name_en": "South China catshark", "sci": "Apristurus sinensis", "family": "猫鲨科", "family_en": "Scyliorhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 8, "name": "中国团扇鳐", "name_en": "fanray", "sci": "Platyrhina sinensis", "family": "團扇鰩科", "family_en": "Platyrhinidae", "order": "电鳐目", "order_en": "Torpediniformes", "iucn": "EN", "cat": "ray"},
{"id": 9, "name": "中国魟", "name_en": "Chinese stingray", "sci": "Dasyatis sinensis", "family": "魟科", "family_en": "Dasyatidae", "order": "鳐目", "order_en": "Rajiformes", "cat": "ray"},
{"id": 10, "name": "中間長吻鰩", "sci": "Dipturus intermedius", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "CR", "cat": "ray"},
{"id": 11, "name": "乌鲨", "name_en": "Blackbelly lanternshark", "sci": "Etmopterus lucifer", "family": "燈籠棘鮫科", "family_en": "Etmopteridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 12, "name": "乔氏银鲛", "sci": "Chimaera jordani", "family": "短鼻银鲛科", "family_en": "Chimaeridae", "order": "银鲛目", "order_en": "Chimaeriformes", "iucn": "DD", "cat": "chimaera"},
{"id": 13, "name": "云纹电鳐", "name_en": "Gulf torpedo", "sci": "Torpedo sinuspersici", "family": "电鳐科", "family_en": "Torpedinidae", "order": "电鳐目", "order_en": "Torpediniformes", "iucn": "DD", "cat": "ray"},
{"id": 14, "name": "亮尾拟小鳍鲨", "name_en": "taillight shark", "sci": "Euprotomicroides zantedeschia", "family": "黑棘鮫科", "family_en": "Dalatiidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 15, "name": "伊氏锯尾鲨", "name_en": "Gecko catshark", "sci": "Galeus eastmani", "family": "Pentanchidae", "family_en": "Pentanchidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 16, "name": "低鰭刺鯊", "name_en": "lowfin gulper shark", "sci": "Centrophorus lusitanicus", "family": "刺鯊科", "family_en": "Centrophoridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "VU", "cat": "shark"},
{"id": 17, "name": "何氏鳐", "sci": "Okamejei hollandi", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "VU", "cat": "ray"},
{"id": 18, "name": "佛氏虎鯊", "name_en": "horn shark", "sci": "Heterodontus francisci", "family": "Heterodontidae", "family_en": "Heterodontidae", "order": "Heterodontiformes", "order_en": "Heterodontiformes", "iucn": "LC", "cat": "shark"},
{"id": 19, "name": "佩氏真鲨", "name_en": "Carcharhinus perezii", "sci": "Carcharhinus perezi", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "EN", "cat": "shark"},
{"id": 20, "name": "侏儒角鯊", "name_en": "Dwarf lanternshark", "sci": "Etmopterus perryi", "family": "燈籠棘鮫科", "family_en": "Etmopteridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 21, "name": "侏斑鬚鯊", "name_en": "dwarf spotted wobbegong", "sci": "Orectolobus parvimaculatus", "family": "鬚鯊科", "family_en": "Orectolobidae", "order": "鬚鮫目", "order_en": "Orectolobiformes", "iucn": "LC", "cat": "shark"},
{"id": 22, "name": "兇猛砂錐齒鯊", "name_en": "smalltooth sand tiger", "sci": "Odontaspis ferox", "family": "锥齿鲨科", "family_en": "Odontaspididae", "order": "鼠鲨目", "order_en": "Lamniformes", "iucn": "EN", "cat": "shark"},
{"id": 23, "name": "光滑強鰭鳐", "name_en": "Southern banded guitarfish", "sci": "Zapteryx xyster", "family": "南犁頭鰩科", "family_en": "Trygonorrhinidae", "order": "犁头鳐目", "order_en": "Rhinopristiformes", "iucn": "VU", "cat": "ray"},
{"id": 24, "name": "光滑長吻鰩", "name_en": "Barndoor skate", "sci": "Dipturus laevis", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 25, "name": "光澤深鰩", "sci": "Pavoraja nitida", "family": "单鳍鳐科", "family_en": "Arhynchobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 26, "name": "光背真鲨", "name_en": "Pacific smalltail shark", "sci": "Carcharhinus cerdale", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "CR", "cat": "shark"},
{"id": 27, "name": "光背長吻鰩", "name_en": "New Zealand smooth skate", "sci": "Dipturus innominatus", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 28, "name": "光鳞鲨", "name_en": "tawny nurse shark", "sci": "Nebrius ferrugineus", "family": "绞口鲨科", "family_en": "Ginglymostomatidae", "order": "鬚鮫目", "order_en": "Orectolobiformes", "iucn": "VU", "cat": "shark"},
{"id": 29, "name": "光齒真鯊", "name_en": "Smoothtooth blacktip shark", "sci": "Carcharhinus leiodon", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "EN", "cat": "shark"},
{"id": 30, "name": "克氏指鳐", "sci": "Dactylobatus clarkii", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 31, "name": "兔子魚", "sci": "Chimaera monstrosa", "family": "短鼻银鲛科", "family_en": "Chimaeridae", "order": "银鲛目", "order_en": "Chimaeriformes", "iucn": "VU", "cat": "chimaera"},
{"id": 32, "name": "公牛鯊", "sci": "Carcharhinus leucas", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "VU", "cat": "shark"},
{"id": 33, "name": "六鳃锯鲨", "name_en": "sixgill sawshark", "sci": "Pliotrema warreni", "family": "锯鲨科", "family_en": "Pristiophoridae", "order": "锯鲨目", "order_en": "Pristiophoriformes", "iucn": "LC", "cat": "shark"},
{"id": 34, "name": "六鳃魟", "name_en": "sixgill stingray", "sci": "Hexatrygon bickelli", "family": "六鰓魟科", "family_en": "Hexatrygonidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 35, "name": "冰島鋸尾鯊", "name_en": "Mouse catshark", "sci": "Galeus murinus", "family": "Pentanchidae", "family_en": "Pentanchidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 36, "name": "利氏龍紋鱝", "name_en": "African wedgefish", "sci": "Rhynchobatus luebberti", "family": "圆犁头鳐科", "family_en": "Rhinidae", "order": "圆犁头鳐目", "order_en": "Rhiniformes", "iucn": "CR", "cat": "ray"},
{"id": 37, "name": "刺網鰩", "name_en": "Spiny deepsea skate", "sci": "Brochiraja spinifera", "family": "单鳍鳐科", "family_en": "Arhynchobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "DD", "cat": "ray"},
{"id": 38, "name": "剑鼻鲨属", "name_en": "Daggernose shark", "sci": "Isogomphodon oxyrhynchus", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "CR", "cat": "shark"},
{"id": 39, "name": "加勒比乌鲨", "name_en": "Caribbean lanternshark", "sci": "Etmopterus hillianus", "family": "燈籠棘鮫科", "family_en": "Etmopteridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 40, "name": "加勒比尖背角鯊", "name_en": "Caribbean roughshark", "sci": "Oxynotus caribbaeus", "family": "粗皮棘鲛科", "family_en": "Oxynotidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 41, "name": "加勒比斜鋸牙鯊", "name_en": "Caribbean sharpnose shark", "sci": "Rhizoprionodon porosus", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "VU", "cat": "shark"},
{"id": 42, "name": "加州大電鱝", "name_en": "Pacific electric ray", "sci": "Torpedo californica", "family": "电鳐科", "family_en": "Torpedinidae", "order": "电鳐目", "order_en": "Torpediniformes", "cat": "ray"},
{"id": 43, "name": "加州扁鲨", "sci": "Squatina californica", "family": "扁鲨科", "family_en": "Squatinidae", "order": "扁鲨目", "order_en": "Squatiniformes", "iucn": "VU", "cat": "shark"},
{"id": 44, "name": "加州星鯊", "name_en": "Grey smooth-hound", "sci": "Mustelus californicus", "family": "皱唇鲨科", "family_en": "Triakidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 45, "name": "加州鲼", "name_en": "bat ray", "sci": "Myliobatis californica", "family": "鲼科", "family_en": "Myliobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 47, "name": "加氏白鰩", "sci": "Leucoraja garmani", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 48, "name": "勃氏角鯊", "name_en": "Longnose spurdog", "sci": "Squalus blainville", "family": "角鯊科", "family_en": "Squalidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "DD", "cat": "shark"},
{"id": 49, "name": "匀棘深水鳐", "sci": "Bathyraja isotrachys", "family": "单鳍鳐科", "family_en": "Arhynchobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 50, "name": "北極鈍頭鳐", "name_en": "Arctic skate", "sci": "Amblyraja hyperborea", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 51, "name": "北河露齒鯊", "name_en": "Northern river shark", "sci": "Glyphis garricki", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "VU", "cat": "shark"},
{"id": 52, "name": "北美星鯊", "name_en": "Gulf smoothhound", "sci": "Mustelus sinusmexicanus", "family": "皱唇鲨科", "family_en": "Triakidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 53, "name": "半帶皺唇鯊", "name_en": "leopard shark", "sci": "Triakis semifasciata", "family": "皱唇鲨科", "family_en": "Triakidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 54, "name": "半鋸鯊", "sci": "Hemipristis serra", "family": "沙條鮫科", "family_en": "Hemigaleidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "cat": "shark"},
{"id": 55, "name": "半鋸齒鯊", "name_en": "Snaggletooth shark", "sci": "Hemipristis elongata", "family": "沙條鮫科", "family_en": "Hemigaleidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "EN", "cat": "shark"},
{"id": 56, "name": "南方烏鯊", "name_en": "Southern lanternshark", "sci": "Etmopterus granulosus", "family": "燈籠棘鮫科", "family_en": "Etmopteridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 57, "name": "南方田氏鯊", "name_en": "Deania quadrispinosum", "sci": "Deania quadrispinosa", "family": "刺鯊科", "family_en": "Centrophoridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "VU", "cat": "shark"},
{"id": 58, "name": "南方龙纹鲼", "sci": "Rhynchobatus australiae", "family": "圆犁头鳐科", "family_en": "Rhinidae", "order": "圆犁头鳐目", "order_en": "Rhiniformes", "iucn": "CR", "cat": "ray"},
{"id": 59, "name": "南極星鯊", "name_en": "Gummy shark", "sci": "Mustelus antarcticus", "family": "皱唇鲨科", "family_en": "Triakidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 60, "name": "南極睡鯊", "name_en": "Southern sleeper shark", "sci": "Somniosus antarcticus", "family": "梦棘鲛科", "family_en": "Somniosidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 61, "name": "南美星鯊", "name_en": "Speckled smooth-hound", "sci": "Mustelus mento", "family": "皱唇鲨科", "family_en": "Triakidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "CR", "cat": "shark"},
{"id": 62, "name": "南部鳐鱼", "name_en": "southern stingray", "sci": "Dasyatis americana", "family": "魟科", "family_en": "Dasyatidae", "order": "鳐目", "order_en": "Rajiformes", "cat": "ray"},
{"id": 63, "name": "南非單鰭電鰩", "name_en": "onefin electric ray", "sci": "Narke capensis", "family": "單鳍电鳐科", "family_en": "Narkidae", "order": "电鳐目", "order_en": "Torpediniformes", "iucn": "LC", "cat": "ray"},
{"id": 64, "name": "卡氏大西洋鳐", "name_en": "Spotback skate", "sci": "Atlantoraja castelnaui", "family": "单鳍鳐科", "family_en": "Arhynchobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "CR", "cat": "ray"},
{"id": 65, "name": "卡氏尖頜烏鯊", "name_en": "viper dogfish", "sci": "Trigonognathus kabeyai", "family": "燈籠棘鮫科", "family_en": "Etmopteridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 66, "name": "印尼長尾鬚鯊", "name_en": "Indonesian speckled carpetshark", "sci": "Hemiscyllium freycineti", "family": "長尾鬚鯊科", "family_en": "Hemiscylliidae", "order": "鬚鮫目", "order_en": "Orectolobiformes", "iucn": "NT", "cat": "shark"},
{"id": 67, "name": "印度後鰭錐齒鯊", "name_en": "Indian sand tiger", "sci": "Carcharias tricuspidatus", "family": "锥齿鲨科", "family_en": "Odontaspididae", "order": "鼠鲨目", "order_en": "Lamniformes", "cat": "shark"},
{"id": 68, "name": "印度斑竹鲨", "name_en": "Slender bamboo shark", "sci": "Chiloscyllium indicum", "family": "長尾鬚鯊科", "family_en": "Hemiscylliidae", "order": "鬚鮫目", "order_en": "Orectolobiformes", "iucn": "VU", "cat": "shark"},
{"id": 69, "name": "印度洋霞鯊", "name_en": "Ornate dogfish", "sci": "Centroscyllium ornatum", "family": "燈籠棘鮫科", "family_en": "Etmopteridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 70, "name": "印度蝠鱝", "name_en": "Bentfin devil ray", "sci": "Mobula thurstoni", "family": "鲼科", "family_en": "Myliobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "CR", "cat": "ray"},
{"id": 72, "name": "叉頭燕魟", "name_en": "Flapnose ray", "sci": "Rhinoptera javanica", "family": "鲼科", "family_en": "Myliobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "EN", "cat": "ray"},
{"id": 73, "name": "及达尖犁头鳐", "name_en": "giant guitarfish", "sci": "Rhynchobatus djiddensis", "family": "圆犁头鳐科", "family_en": "Rhinidae", "order": "圆犁头鳐目", "order_en": "Rhiniformes", "iucn": "CR", "cat": "ray"},
{"id": 75, "name": "双斑鳐", "name_en": "big skate", "sci": "Raja binoculata", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "cat": "ray"},
{"id": 76, "name": "古巴角鯊", "name_en": "Cuban dogfish", "sci": "Squalus cubensis", "family": "角鯊科", "family_en": "Squalidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 79, "name": "史氏深海鰩", "sci": "Bathyraja smithii", "family": "单鳍鳐科", "family_en": "Arhynchobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 81, "name": "后鳍尖吻银鲛", "sci": "Harriotta raleighana", "family": "长吻银鲛科", "family_en": "Rhinochimaeridae", "order": "银鲛目", "order_en": "Chimaeriformes", "iucn": "LC", "cat": "chimaera"},
{"id": 104, "name": "多眼齒鰩", "name_en": "Argus skate", "sci": "Dipturus polyommata", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "cat": "ray"},
{"id": 105, "name": "大吻光尾鲨", "name_en": "flathead catshark", "sci": "Apristurus macrorhynchus", "family": "猫鲨科", "family_en": "Scyliorhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 108, "name": "大白鲨", "name_en": "great white shark", "sci": "Carcharodon carcharias", "family": "鼠鲨科", "family_en": "Lamnidae", "order": "鼠鲨目", "order_en": "Lamniformes", "iucn": "VU", "cat": "shark"},
{"id": 109, "name": "大眼六鳃鲨", "name_en": "bigeyed sixgill shark", "sci": "Hexanchus nakamurai", "family": "六鳃鲨科", "family_en": "Hexanchidae", "order": "六鳃鲨目", "order_en": "Hexanchiformes", "iucn": "NT", "cat": "shark"},
{"id": 110, "name": "大眼真鲨", "sci": "Carcharhinus macrops", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "cat": "shark"},
{"id": 111, "name": "大眼砂錐齒鯊", "name_en": "bigeye sand tiger", "sci": "Odontaspis noronhai", "family": "锥齿鲨科", "family_en": "Odontaspididae", "order": "鼠鲨目", "order_en": "Lamniformes", "iucn": "LC", "cat": "shark"},
{"id": 112, "name": "大眼角鯊", "sci": "Squalus megalops", "family": "角鯊科", "family_en": "Squalidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 113, "name": "大眼长尾鲨", "name_en": "bigeye thresher", "sci": "Alopias superciliosus", "family": "长尾鲨科", "family_en": "Alopiidae", "order": "鼠鲨目", "order_en": "Lamniformes", "iucn": "VU", "cat": "shark"},
{"id": 114, "name": "大西洋刺鯊", "name_en": "gulper shark", "sci": "Centrophorus granulosus", "family": "刺鯊科", "family_en": "Centrophoridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "EN", "cat": "shark"},
{"id": 115, "name": "大西洋副沙条鲨", "name_en": "Atlantic weasel shark", "sci": "Paragaleus pectoralis", "family": "沙條鮫科", "family_en": "Hemigaleidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "EN", "cat": "shark"},
{"id": 116, "name": "大西洋拟犁头鳐", "sci": "Pseudobatos lentiginosus", "family": "犁头鳐科", "family_en": "Rhinobatidae", "order": "犁头鳐目", "order_en": "Rhinobatiformes", "iucn": "VU", "cat": "shark"},
{"id": 118, "name": "大西洋鋸尾鯊", "name_en": "Atlantic sawtail catshark", "sci": "Galeus atlanticus", "family": "Pentanchidae", "family_en": "Pentanchidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "NT", "cat": "shark"},
{"id": 119, "name": "大西洋魟", "name_en": "Atlantic stingray", "sci": "Dasyatis sabina", "family": "魟科", "family_en": "Dasyatidae", "order": "鳐目", "order_en": "Rajiformes", "cat": "ray"},
{"id": 120, "name": "大青鲨", "sci": "Prionace glauca", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "NT", "cat": "shark"},
{"id": 121, "name": "大鼻穀鰩", "sci": "Zearaja nasuta", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "cat": "ray"},
{"id": 122, "name": "大齒鋸鰩", "name_en": "large-tooth sawfish", "sci": "Pristis perotteti", "family": "锯鳐科", "family_en": "Pristidae", "order": "犁头鳐目", "order_en": "Rhinopristiformes", "cat": "ray"},
{"id": 123, "name": "天狗老板鯆", "sci": "Dipturus tengu", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "NT", "cat": "ray"},
{"id": 124, "name": "太平洋斜鋸牙鯊", "name_en": "Pacific sharpnose shark", "sci": "Rhizoprionodon longurio", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "VU", "cat": "shark"},
{"id": 125, "name": "太平洋睡鯊", "sci": "Somniosus pacificus", "family": "梦棘鲛科", "family_en": "Somniosidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "NT", "cat": "shark"},
{"id": 126, "name": "太平洋窄尾𫚉", "name_en": "Pacific chupare", "sci": "Himantura pacifica", "family": "魟科", "family_en": "Dasyatidae", "order": "鳐目", "order_en": "Rajiformes", "cat": "ray"},
{"id": 127, "name": "太平洋長鼻銀鮫", "sci": "Rhinochimaera pacifica", "family": "长吻银鲛科", "family_en": "Rhinochimaeridae", "order": "银鲛目", "order_en": "Chimaeriformes", "iucn": "LC", "cat": "chimaera"},
{"id": 128, "name": "太平洋鼠鯊", "name_en": "salmon shark", "sci": "Lamna ditropis", "family": "鼠鲨科", "family_en": "Lamnidae", "order": "鼠鲨目", "order_en": "Lamniformes", "iucn": "LC", "cat": "shark"},
{"id": 129, "name": "头绒毛鲨", "name_en": "draughtsboard shark", "sci": "Cephaloscyllium isabellum", "family": "猫鲨科", "family_en": "Scyliorhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 130, "name": "奈氏魟", "name_en": "Blackish stingray", "sci": "Dasyatis navarrae", "family": "魟科", "family_en": "Dasyatidae", "order": "鳐目", "order_en": "Rajiformes", "cat": "ray"},
{"id": 131, "name": "奥斯蒂诺鲨属", "sci": "Ostenoselache stenosoma", "family": "Ostenoselachidae", "family_en": "Ostenoselachidae", "cat": "shark"},
{"id": 132, "name": "奥氏江魟", "sci": "Potamotrygon orbignyi", "family": "江𫚉科", "family_en": "Potamotrygonidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 133, "name": "奧氏兔銀鮫", "sci": "Hydrolagus ogilbyi", "family": "短鼻银鲛科", "family_en": "Chimaeridae", "order": "银鲛目", "order_en": "Chimaeriformes", "iucn": "VU", "cat": "chimaera"},
{"id": 134, "name": "妆饰鬚鯊", "name_en": "ornate wobbegong", "sci": "Orectolobus ornatus", "family": "鬚鯊科", "family_en": "Orectolobidae", "order": "鬚鮫目", "order_en": "Orectolobiformes", "iucn": "LC", "cat": "shark"},
{"id": 135, "name": "妖怪尖犁头鳐", "sci": "Rhynchobatus mononoke", "family": "圆犁头鳐科", "family_en": "Rhinidae", "order": "圆犁头鳐目", "order_en": "Rhiniformes", "cat": "ray"},
{"id": 136, "name": "姥鲨", "name_en": "basking shark", "sci": "Cetorhinus maximus", "family": "姥鲨科", "family_en": "Cetorhinidae", "order": "鼠鲨目", "order_en": "Lamniformes", "iucn": "EN", "cat": "shark"},
{"id": 137, "name": "姬蝠鲼", "name_en": "devil fish", "sci": "Mobula mobular", "family": "鲼科", "family_en": "Myliobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "CR", "cat": "ray"},
{"id": 138, "name": "威氏星鯊", "name_en": "White-fin smooth-hound", "sci": "Mustelus widodoi", "family": "皱唇鲨科", "family_en": "Triakidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "VU", "cat": "shark"},
{"id": 139, "name": "婆罗真鲨", "name_en": "Borneo shark", "sci": "Carcharhinus borneensis", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "CR", "cat": "shark"},
{"id": 140, "name": "安德森電鰩", "name_en": "Florida torpedo", "sci": "Torpedo andersoni", "family": "电鳐科", "family_en": "Torpedinidae", "order": "电鳐目", "order_en": "Torpediniformes", "iucn": "LC", "cat": "ray"},
{"id": 141, "name": "安格斯迪鲨", "sci": "Carcharocles angustidens", "family": "耳齿鲨科", "family_en": "Otodontidae", "order": "鼠鲨目", "order_en": "Lamniformes", "cat": "shark"},
{"id": 142, "name": "安格斯迪鲨", "sci": "Otodus angustidens", "family": "耳齿鲨科", "family_en": "Otodontidae", "order": "鼠鲨目", "order_en": "Lamniformes", "cat": "shark"},
{"id": 143, "name": "安的列斯鋸尾鯊", "name_en": "Antilles catshark", "sci": "Galeus antillensis", "family": "Pentanchidae", "family_en": "Pentanchidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 144, "name": "宫齿鲛属", "sci": "Delphyodontos dacriformes", "cat": "shark"},
{"id": 145, "name": "宽尾拟角鲨", "name_en": "spined pygmy shark", "sci": "Squaliolus laticaudus", "family": "黑棘鮫科", "family_en": "Dalatiidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 146, "name": "宽尾斜齿鲨", "name_en": "Spadenose shark", "sci": "Scoliodon laticaudus", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "NT", "cat": "shark"},
{"id": 147, "name": "宽纹虎鲨", "name_en": "Japanese bullhead shark", "sci": "Heterodontus japonicus", "family": "Heterodontidae", "family_en": "Heterodontidae", "order": "Heterodontiformes", "order_en": "Heterodontiformes", "iucn": "LC", "cat": "shark"},
{"id": 148, "name": "宽鳍鲨", "sci": "Lamiopsis temminckii", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "EN", "cat": "shark"},
{"id": 149, "name": "密西西比软鳞铠鲨", "name_en": "American pocket shark", "sci": "Mollisquama mississippiensis", "family": "黑棘鮫科", "family_en": "Dalatiidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 150, "name": "密點白鰩", "sci": "Leucoraja ocellata", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "EN", "cat": "ray"},
{"id": 151, "name": "寬鼻星鯊", "name_en": "starry smooth-hound", "sci": "Mustelus asterias", "family": "皱唇鲨科", "family_en": "Triakidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "NT", "cat": "shark"},
{"id": 152, "name": "小乌鲨", "name_en": "smooth lanternshark", "sci": "Etmopterus pusillus", "family": "燈籠棘鮫科", "family_en": "Etmopteridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 153, "name": "小口异鳞鲨", "name_en": "Smallmouth velvet dogfish", "sci": "Scymnodon obscurus", "family": "梦棘鲛科", "family_en": "Somniosidae", "order": "角鲨目", "order_en": "Squaliformes", "cat": "shark"},
{"id": 154, "name": "小口沙條鮫", "name_en": "sicklefin weasel shark", "sci": "Hemigaleus microstoma", "family": "沙條鮫科", "family_en": "Hemigaleidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "VU", "cat": "shark"},
{"id": 155, "name": "小口雙鰭電鰩", "name_en": "Giant electric ray", "sci": "Narcine entemedor", "family": "双鳍电鳐科", "family_en": "Narcinidae", "order": "电鳐目", "order_en": "Torpediniformes", "iucn": "VU", "cat": "ray"},
{"id": 156, "name": "小尾甕鰩", "sci": "Okamejei leptoura", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 157, "name": "小尾真鲨", "name_en": "smalltail shark", "sci": "Carcharhinus porosus", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "CR", "cat": "shark"},
{"id": 158, "name": "小星加州鰩", "sci": "Raja stellulata", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "cat": "ray"},
{"id": 159, "name": "小棘短鰩", "sci": "Breviraja spinosa", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 160, "name": "小眼星鯊", "name_en": "Smalleye smooth-hound", "sci": "Mustelus higmani", "family": "皱唇鲨科", "family_en": "Triakidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "EN", "cat": "shark"},
{"id": 161, "name": "小眼雙髻鯊", "name_en": "smalleye hammerhead", "sci": "Sphyrna tudes", "family": "双髻鲨科", "family_en": "Sphyrnidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "CR", "cat": "shark"},
{"id": 162, "name": "小睛斑鰩", "name_en": "Smalleyed ray", "sci": "Raja microocellata", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "NT", "cat": "ray"},
{"id": 163, "name": "小雙鰭電鰩", "name_en": "Lesser electric ray", "sci": "Narcine bancroftii", "family": "双鳍电鳐科", "family_en": "Narcinidae", "order": "电鳐目", "order_en": "Torpediniformes", "iucn": "LC", "cat": "ray"},
{"id": 164, "name": "小頭睡鯊", "name_en": "Greenland shark", "sci": "Somniosus microcephalus", "family": "梦棘鲛科", "family_en": "Somniosidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "VU", "cat": "shark"},
{"id": 165, "name": "小鰭刺鯊", "name_en": "smallfin gulper shark", "sci": "Centrophorus moluccensis", "family": "刺鯊科", "family_en": "Centrophoridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "VU", "cat": "shark"},
{"id": 166, "name": "小鰭睡鯊", "name_en": "Little sleeper shark", "sci": "Somniosus rostratus", "family": "梦棘鲛科", "family_en": "Somniosidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 167, "name": "小齿锯鳐", "name_en": "common sawfish", "sci": "Pristis microdon", "family": "锯鳐科", "family_en": "Pristidae", "order": "犁头鳐目", "order_en": "Rhinopristiformes", "cat": "ray"},
{"id": 168, "name": "尖同鰭鰩", "name_en": "bignose fanskate", "sci": "Sympterygia acuta", "family": "单鳍鳐科", "family_en": "Arhynchobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "CR", "cat": "ray"},
{"id": 169, "name": "尖吻七鳃鲨", "name_en": "sharpnose sevengill shark", "sci": "Heptranchias perlo", "family": "六鳃鲨科", "family_en": "Hexanchidae", "order": "六鳃鲨目", "order_en": "Hexanchiformes", "iucn": "NT", "cat": "shark"},
{"id": 170, "name": "尖吻土魟", "sci": "Dasyatis acutirostra", "family": "魟科", "family_en": "Dasyatidae", "order": "鳐目", "order_en": "Rajiformes", "cat": "ray"},
{"id": 171, "name": "尖吻斜鋸牙鯊", "sci": "Rhizoprionodon acutus", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "VU", "cat": "shark"},
{"id": 172, "name": "尖吻角鯊", "sci": "Squalus acutirostris", "family": "角鯊科", "family_en": "Squalidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "DD", "cat": "shark"},
{"id": 173, "name": "尖吻鲭鲨", "name_en": "shortfin mako shark", "sci": "Isurus oxyrinchus", "family": "鼠鲨科", "family_en": "Lamnidae", "order": "鼠鲨目", "order_en": "Lamniformes", "iucn": "EN", "cat": "shark"},
{"id": 174, "name": "尖嘴魟", "name_en": "Pale-edged stingray", "sci": "Dasyatis zugei", "family": "魟科", "family_en": "Dasyatidae", "order": "鳐目", "order_en": "Rajiformes", "cat": "ray"},
{"id": 175, "name": "尖背角鯊", "name_en": "angular roughshark", "sci": "Oxynotus centrina", "family": "粗皮棘鲛科", "family_en": "Oxynotidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "EN", "cat": "shark"},
{"id": 176, "name": "尖銳錐齒鯊", "sci": "Carcharias cuspidatus", "family": "锥齿鲨科", "family_en": "Odontaspididae", "order": "鼠鲨目", "order_en": "Lamniformes", "cat": "shark"},
{"id": 177, "name": "尖長吻鰩", "sci": "Dipturus oxyrinchus", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "VU", "cat": "ray"},
{"id": 178, "name": "尖鰭刺鯊", "name_en": "needle dogfish", "sci": "Centrophorus acus", "family": "刺鯊科", "family_en": "Centrophoridae", "order": "角鲨目", "order_en": "Squaliformes", "cat": "shark"},
{"id": 179, "name": "尖齒星鯊", "name_en": "Sharptooth smooth-hound", "sci": "Mustelus dorsalis", "family": "皱唇鲨科", "family_en": "Triakidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "VU", "cat": "shark"},
{"id": 180, "name": "尖齿异鳞鲨", "name_en": "Knifetooth dogfish", "sci": "Scymnodon ringens", "family": "梦棘鲛科", "family_en": "Somniosidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "VU", "cat": "shark"},
{"id": 181, "name": "巨口鲨", "name_en": "Megamouth shark", "sci": "Megachasma pelagios", "family": "巨口鲨科", "family_en": "Megachasmidae", "order": "鼠鲨目", "order_en": "Lamniformes", "iucn": "LC", "cat": "shark"},
{"id": 182, "name": "巨齒鯊", "name_en": "megalodon", "sci": "Otodus megalodon", "family": "耳齿鲨科", "family_en": "Otodontidae", "order": "鼠鲨目", "order_en": "Lamniformes", "cat": "shark"},
{"id": 183, "name": "巴布亞長尾鬚鯊", "name_en": "Papuan epaulette shark", "sci": "Hemiscyllium hallstromi", "family": "長尾鬚鯊科", "family_en": "Hemiscylliidae", "order": "鬚鮫目", "order_en": "Orectolobiformes", "iucn": "VU", "cat": "shark"},
{"id": 184, "name": "巴氏細鰩", "name_en": "Bigthorn skate", "sci": "Rajella barnardi", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 185, "name": "巴西副江魟", "sci": "Paratrygon aiereba", "family": "江𫚉科", "family_en": "Potamotrygonidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "CR", "cat": "ray"},
{"id": 186, "name": "巴西大西洋鳐", "name_en": "Eyespot skate", "sci": "Atlantoraja cyclophora", "family": "单鳍鳐科", "family_en": "Arhynchobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "EN", "cat": "ray"},
{"id": 187, "name": "巴西斜鋸牙鯊", "name_en": "Brazilian sharpnose shark", "sci": "Rhizoprionodon lalandii", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "VU", "cat": "shark"},
{"id": 188, "name": "巴西达摩鲨", "sci": "Isistius brasiliensis", "family": "黑棘鮫科", "family_en": "Dalatiidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 189, "name": "巴西雙鰭電鰩", "sci": "Narcine brasiliensis", "family": "双鳍电鳐科", "family_en": "Narcinidae", "order": "电鳐目", "order_en": "Torpediniformes", "iucn": "NT", "cat": "ray"},
{"id": 190, "name": "布氏乌鲨", "name_en": "Lined lanternshark", "sci": "Etmopterus bullisi", "family": "燈籠棘鮫科", "family_en": "Etmopteridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 191, "name": "帆鰭尖背角鯊", "name_en": "Sailfin roughshark", "sci": "Oxynotus paradoxus", "family": "粗皮棘鲛科", "family_en": "Oxynotidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "VU", "cat": "shark"},
{"id": 192, "name": "希氏拟铠鲨", "name_en": "Sherwood dogfish", "sci": "Scymnodalatias sherwoodi", "family": "梦棘鲛科", "family_en": "Somniosidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "DD", "cat": "shark"},
{"id": 193, "name": "希氏齒鰩", "sci": "Dipturus healdi", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "cat": "ray"},
{"id": 194, "name": "帝汶铲吻犁头鳐", "name_en": "spotted shovelnose ray", "sci": "Aptychotrema timorensis", "family": "南犁頭鰩科", "family_en": "Trygonorrhinidae", "order": "犁头鳐目", "order_en": "Rhinopristiformes", "iucn": "VU", "cat": "ray"},
{"id": 195, "name": "帝王魟", "sci": "Potamotrygon falkneri", "family": "江𫚉科", "family_en": "Potamotrygonidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 196, "name": "带纹扁魟", "sci": "Urolophus cruciatus", "family": "扁魟科", "family_en": "Urolophidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 197, "name": "帶紋長鬚貓鯊", "sci": "Poroderma africanum", "family": "猫鲨科", "family_en": "Scyliorhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 198, "name": "平滑真鲨", "name_en": "silky shark", "sci": "Carcharhinus falciformis", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "VU", "cat": "shark"},
{"id": 199, "name": "平背鯆魮", "name_en": "Ocellate spot skate", "sci": "Okamejei kenojei", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "VU", "cat": "ray"},
{"id": 200, "name": "廣鼻曲齒鮫", "sci": "Loxodon macrorhinus", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "NT", "cat": "shark"},
{"id": 201, "name": "弗氏鋸尾鯊", "sci": "Galeus friedrichi", "family": "Pentanchidae", "family_en": "Pentanchidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "cat": "shark"},
{"id": 202, "name": "弗氏鲼", "sci": "Myliobatis freminvillei", "family": "鲼科", "family_en": "Myliobatidae", "order": "鱝目", "order_en": "Myliobatiformes", "iucn": "VU", "cat": "ray"},
{"id": 203, "name": "弧形長尾鯊", "name_en": "common thresher", "sci": "Alopias vulpinus", "family": "长尾鲨科", "family_en": "Alopiidae", "order": "鼠鲨目", "order_en": "Lamniformes", "iucn": "VU", "cat": "shark"},
{"id": 204, "name": "忍者燈籠鯊", "name_en": "Ninja lanternshark", "sci": "Etmopterus benchleyi", "family": "燈籠棘鮫科", "family_en": "Etmopteridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 205, "name": "恆河露齒鯊", "sci": "Glyphis gangeticus", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "CR", "cat": "shark"},
{"id": 206, "name": "恩氏齒鰩", "sci": "Dentiraja endeavouri", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "NT", "cat": "ray"},
{"id": 207, "name": "惠氏星鯊", "name_en": "Humpback smooth-hound", "sci": "Mustelus whitneyi", "family": "皱唇鲨科", "family_en": "Triakidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "CR", "cat": "shark"},
{"id": 208, "name": "懷特氏棘尾鰩", "sci": "Spiniraja whitleyi", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "VU", "cat": "ray"},
{"id": 209, "name": "戴氏扁鲨", "sci": "Squatina david", "family": "扁鲨科", "family_en": "Squatinidae", "order": "扁鲨目", "order_en": "Squatiniformes", "iucn": "NT", "cat": "shark"},
{"id": 210, "name": "扁吻光尾鲨", "name_en": "spatulasnout catshark", "sci": "Apristurus platyrhynchus", "family": "猫鲨科", "family_en": "Scyliorhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 211, "name": "扁头哈那鲨", "name_en": "broadnose sevengill shark", "sci": "Notorynchus cepedianus", "family": "六鳃鲨科", "family_en": "Hexanchidae", "order": "六鳃鲨目", "order_en": "Hexanchiformes", "iucn": "VU", "cat": "shark"},
{"id": 212, "name": "扁鯊", "sci": "Squatina squatina", "family": "扁鲨科", "family_en": "Squatinidae", "order": "扁鲨目", "order_en": "Squatiniformes", "iucn": "CR", "cat": "shark"},
{"id": 213, "name": "托氏魟", "name_en": "Tortonese's stingray", "sci": "Dasyatis tortonesei", "family": "魟科", "family_en": "Dasyatidae", "order": "鱝目", "order_en": "Myliobatiformes", "iucn": "DD", "cat": "ray"},
{"id": 214, "name": "指鰩", "sci": "Dactylobatus armatus", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 215, "name": "挪威長吻鰩", "sci": "Dipturus nidarosiensis", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "EN", "cat": "ray"},
{"id": 216, "name": "擬團扇鰩", "name_en": "thornback guitarfish", "sci": "Platyrhinoidis triseriata", "family": "團扇鰩科", "family_en": "Platyrhinidae", "order": "电鳐目", "order_en": "Torpediniformes", "iucn": "LC", "cat": "ray"},
{"id": 217, "name": "擬皺唇鯊屬", "name_en": "false catshark", "sci": "Pseudotriakis microdon", "family": "拟皱唇鲨科", "family_en": "Pseudotriakidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 218, "name": "斑点鼠鱼", "name_en": "spotted ratfish", "sci": "Hydrolagus colliei", "family": "短鼻银鲛科", "family_en": "Chimaeridae", "order": "银鲛目", "order_en": "Chimaeriformes", "iucn": "LC", "cat": "chimaera"},
{"id": 219, "name": "斑紋南犁頭鰩", "sci": "Trygonorrhina fasciata", "family": "南犁頭鰩科", "family_en": "Trygonorrhinidae", "order": "犁头鳐目", "order_en": "Rhinopristiformes", "iucn": "LC", "cat": "ray"},
{"id": 220, "name": "斑纹犁头鳐", "name_en": "Ringstraked guitarfish", "sci": "Rhinobatos hynnicephalus", "family": "犁头鳐科", "family_en": "Rhinobatidae", "order": "犁头鳐目", "order_en": "Rhinobatiformes", "iucn": "EN", "cat": "shark"},
{"id": 221, "name": "斑纹须鲨", "name_en": "spotted wobbegong", "sci": "Orectolobus maculatus", "family": "鬚鯊科", "family_en": "Orectolobidae", "order": "鬚鮫目", "order_en": "Orectolobiformes", "iucn": "LC", "cat": "shark"},
{"id": 222, "name": "斑鲨", "name_en": "Coral catshark", "sci": "Atelomycterus marmoratus", "family": "猫鲨科", "family_en": "Scyliorhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "NT", "cat": "shark"},
{"id": 223, "name": "斑鳍光唇鲨", "name_en": "Pygmy ribbontail catshark", "sci": "Eridacnis radcliffei", "family": "原鲨科", "family_en": "Proscylliidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 224, "name": "斑點圓吻貓鯊", "name_en": "Australian spotted catshark", "sci": "Asymbolus analis", "family": "猫鲨科", "family_en": "Scyliorhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 225, "name": "斯普兰汀乌鲨", "name_en": "Splendid lanternshark", "sci": "Etmopterus splendidus", "family": "燈籠棘鮫科", "family_en": "Etmopteridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 226, "name": "斯氏深海鰩", "sci": "Bathyraja smirnovi", "family": "单鳍鳐科", "family_en": "Arhynchobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "NT", "cat": "ray"},
{"id": 228, "name": "斯氏鰩", "sci": "Raja straeleni", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "NT", "cat": "ray"},
{"id": 229, "name": "斯科比砂鰩", "sci": "Psammobatis scobina", "family": "单鳍鳐科", "family_en": "Arhynchobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 230, "name": "新月星鯊", "name_en": "Sicklefin smooth-hound", "sci": "Mustelus lunulatus", "family": "皱唇鲨科", "family_en": "Triakidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "NT", "cat": "shark"},
{"id": 231, "name": "新西蘭星鯊", "name_en": "Spotted estuary smooth-hound", "sci": "Mustelus lenticulatus", "family": "皱唇鲨科", "family_en": "Triakidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 233, "name": "无沟双髻鲨", "name_en": "great hammerhead", "sci": "Sphyrna mokarran", "family": "双髻鲨科", "family_en": "Sphyrnidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "CR", "cat": "shark"},
{"id": 234, "name": "日光長吻鰩", "sci": "Dipturus apricus", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 235, "name": "日本尖背角鯊", "name_en": "Japanese roughshark", "sci": "Oxynotus japonicus", "family": "粗皮棘鲛科", "family_en": "Oxynotidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "VU", "cat": "shark"},
{"id": 236, "name": "日本扁鲨", "sci": "Squatina japonica", "family": "扁鲨科", "family_en": "Squatinidae", "order": "扁鲨目", "order_en": "Squatiniformes", "iucn": "CR", "cat": "shark"},
{"id": 237, "name": "日本橙黄鲨", "name_en": "saddle carpetshark", "sci": "Cirrhoscyllium japonicum", "family": "须喉鲛科", "family_en": "Parascylliidae", "order": "鬚鮫目", "order_en": "Orectolobiformes", "iucn": "LC", "cat": "shark"},
{"id": 238, "name": "日本燕魟", "sci": "Gymnura japonica", "family": "燕魟科", "family_en": "Gymnuridae", "order": "鱝目", "order_en": "Myliobatiformes", "iucn": "VU", "cat": "ray"},
{"id": 239, "name": "日本蝠鲼", "name_en": "Spinetail mobula", "sci": "Mobula japanica", "family": "鲼科", "family_en": "Myliobatidae", "order": "鱝目", "order_en": "Myliobatiformes", "iucn": "NT", "cat": "ray"},
{"id": 240, "name": "日本角鯊", "name_en": "Japanese spurdog", "sci": "Squalus japonicus", "family": "角鯊科", "family_en": "Squalidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "EN", "cat": "shark"},
{"id": 241, "name": "日本锯尾鲨", "name_en": "Broadfin sawtail catshark", "sci": "Galeus nipponensis", "family": "Pentanchidae", "family_en": "Pentanchidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 242, "name": "日本锯鲨", "name_en": "Japanese sawshark", "sci": "Pristiophorus japonicus", "family": "锯鲨科", "family_en": "Pristiophoridae", "order": "锯鲨目", "order_en": "Pristiophoriformes", "iucn": "LC", "cat": "shark"},
{"id": 243, "name": "日本電鱝", "name_en": "Japanese sleeper ray", "sci": "Narke japonica", "family": "單鳍电鳐科", "family_en": "Narkidae", "order": "电鳐目", "order_en": "Torpediniformes", "iucn": "VU", "cat": "ray"},
{"id": 244, "name": "日本须鲨", "name_en": "Japanese wobbegong", "sci": "Orectolobus japonicus", "family": "鬚鯊科", "family_en": "Orectolobidae", "order": "鬚鮫目", "order_en": "Orectolobiformes", "iucn": "LC", "cat": "shark"},
{"id": 245, "name": "昆士兰锯鳐", "name_en": "dwarf sawfish", "sci": "Pristis clavata", "family": "锯鳐科", "family_en": "Pristidae", "order": "犁头鳐目", "order_en": "Rhinopristiformes", "iucn": "CR", "cat": "ray"},
{"id": 246, "name": "昆士蘭真鯊", "name_en": "Creek whaler", "sci": "Carcharhinus fitzroyensis", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 247, "name": "昆士蘭長吻鰩", "sci": "Dipturus queenslandicus", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "DD", "cat": "ray"},
{"id": 248, "name": "星云扁鲨", "sci": "Squatina nebulosa", "family": "扁鲨科", "family_en": "Squatinidae", "order": "扁鲨目", "order_en": "Squatiniformes", "iucn": "EN", "cat": "shark"},
{"id": 249, "name": "星斑鰩", "sci": "Raja asterias", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 250, "name": "星鯊", "name_en": "common smooth-hound", "sci": "Mustelus mustelus", "family": "皱唇鲨科", "family_en": "Triakidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "EN", "cat": "shark"},
{"id": 251, "name": "普氏拟犁头鳐", "sci": "Pseudobatos prahli", "family": "犁头鳐科", "family_en": "Rhinobatidae", "order": "犁头鳐目", "order_en": "Rhinobatiformes", "iucn": "VU", "cat": "shark"},
{"id": 252, "name": "普通電鰩", "name_en": "common torpedo", "sci": "Torpedo torpedo", "family": "电鳐科", "family_en": "Torpedinidae", "order": "电鳐目", "order_en": "Torpediniformes", "iucn": "VU", "cat": "ray"},
{"id": 253, "name": "晴斑長吻鰩", "name_en": "Slimeskate", "sci": "Dipturus pullopunctatus", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 254, "name": "晶吻鰩", "name_en": "Clearnose skate", "sci": "Raja eglanteria", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "cat": "ray"},
{"id": 255, "name": "智利深海鰩", "sci": "Bathyraja magellanica", "family": "单鳍鳐科", "family_en": "Arhynchobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 256, "name": "朝鮮鰩屬", "sci": "Hongeo koreana", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "CR", "cat": "ray"},
{"id": 257, "name": "杜氏南犁頭鰩", "sci": "Trygonorrhina dumerilii", "family": "南犁頭鰩科", "family_en": "Trygonorrhinidae", "order": "犁头鳐目", "order_en": "Rhinopristiformes", "iucn": "LC", "cat": "ray"},
{"id": 258, "name": "杜氏扁鲨", "sci": "Squatina dumeril", "family": "扁鲨科", "family_en": "Squatinidae", "order": "扁鲨目", "order_en": "Squatiniformes", "iucn": "LC", "cat": "shark"},
{"id": 259, "name": "杜氏真鲨", "name_en": "Whitecheek shark", "sci": "Carcharhinus dussumieri", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "EN", "cat": "shark"},
{"id": 260, "name": "条纹斑竹鲨", "name_en": "Whitespotted bamboo shark", "sci": "Chiloscyllium plagiosum", "family": "長尾鬚鯊科", "family_en": "Hemiscylliidae", "order": "鬚鮫目", "order_en": "Orectolobiformes", "iucn": "NT", "cat": "shark"},
{"id": 261, "name": "枪头真鲨", "name_en": "hardnose shark", "sci": "Carcharhinus macloti", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "NT", "cat": "shark"},
{"id": 262, "name": "柠檬鲨", "sci": "Negaprion brevirostris", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "VU", "cat": "shark"},
{"id": 263, "name": "查菲窄尾魟", "name_en": "Giant freshwater stingray", "sci": "Himantura polylepis", "family": "魟科", "family_en": "Dasyatidae", "order": "鱝目", "order_en": "Myliobatiformes", "cat": "ray"},
{"id": 264, "name": "查菲窄尾𫚉", "sci": "Himantura chaophraya", "family": "魟科", "family_en": "Dasyatidae", "order": "鱝目", "order_en": "Myliobatiformes", "cat": "ray"},
{"id": 265, "name": "格氏長吻鰩", "sci": "Dipturus grahami", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 266, "name": "棘尾深海鰩", "sci": "Bathyraja spinicauda", "family": "单鳍鳐科", "family_en": "Arhynchobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "NT", "cat": "ray"},
{"id": 267, "name": "棘深海鰩", "name_en": "Pacific white skate", "sci": "Bathyraja spinosissima", "family": "单鳍鳐科", "family_en": "Arhynchobatidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "LC", "cat": "ray"},
{"id": 268, "name": "棘背鈍頭鳐", "name_en": "Thorny skate", "sci": "Amblyraja radiata", "family": "鳐科", "family_en": "Rajidae", "order": "鳐目", "order_en": "Rajiformes", "iucn": "VU", "cat": "ray"},
{"id": 270, "name": "棘鳞乌鲨", "name_en": "Great lanternshark", "sci": "Etmopterus princeps", "family": "燈籠棘鮫科", "family_en": "Etmopteridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 272, "name": "横纹前鳍鲼", "sci": "Pteromylaeus bovinus", "family": "鲼科", "family_en": "Myliobatidae", "order": "鱝目", "order_en": "Myliobatiformes", "cat": "ray"},
{"id": 273, "name": "櫛齒鋸鰩", "name_en": "smalltooth sawfish", "sci": "Pristis pectinata", "family": "锯鳐科", "family_en": "Pristidae", "order": "犁头鳐目", "order_en": "Rhinopristiformes", "iucn": "CR", "cat": "ray"},
{"id": 274, "name": "欧氏尖吻鲛", "name_en": "goblin shark", "sci": "Mitsukurina owstoni", "family": "尖吻鮫科", "family_en": "Mitsukurinidae", "order": "鼠鲨目", "order_en": "Lamniformes", "iucn": "LC", "cat": "shark"},
{"id": 275, "name": "欧氏荆鲨", "sci": "Centroscymnus owstonii", "family": "梦棘鲛科", "family_en": "Somniosidae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "VU", "cat": "shark"},
{"id": 277, "name": "比氏燈籠棘鮫", "name_en": "Blurred lanternshark", "sci": "Etmopterus bigelowi", "family": "燈籠棘鮫科", "family_en": "Etmopteridae", "order": "角鲨目", "order_en": "Squaliformes", "iucn": "LC", "cat": "shark"},
{"id": 278, "name": "沃氏鬚鯊", "name_en": "northern wobbegong", "sci": "Orectolobus wardi", "family": "鬚鯊科", "family_en": "Orectolobidae", "order": "鬚鮫目", "order_en": "Orectolobiformes", "iucn": "LC", "cat": "shark"},
{"id": 279, "name": "沙拉真鲨", "sci": "Carcharhinus sorrah", "family": "真鲨科", "family_en": "Carcharhinidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "NT", "cat": "shark"},
{"id": 280, "name": "沙氏锯尾鲨", "name_en": "Blacktip sawtail catshark", "sci": "Galeus sauteri", "family": "Pentanchidae", "family_en": "Pentanchidae", "order": "真鲨目", "order_en": "Carcharhiniformes", "iucn": "LC", "cat": "shark"},
{"id": 281, "name": "沙虎鯊", "name_en": "sand tiger shark", "sci": "Carcharias taurus", "family": "锥齿鲨科", "family_en": "Odontaspididae", "order": "鼠鲨目", "order_en": "Lamniformes", "iucn": "CR", "cat": "shark"}
];
